### ISSUE TITLE
fluidd UI keeps resetting randomly

### ISSUE THREAD

**Issue by petemagnusson** [fluidd-core/fluidd#1010]
Hi, 
Every now and again my fluidd installation keeps resetting the UI.
Layout
Macros (categories) 
Theme
Thermal Presets.

Everything that is in the cfg and txt files are of course untouched.

Not a major problem but just a bit of a pain to setup again :)

I have tried different mSD cards and also two different pis ( 3 initially and now a 4 ).

I have not really looked at the logs but happy to share if you could point me to which one would be helpful.

Thanks and i really appreciator the work and usefulness of fluidd so huge thanks for all your work! 

Software:
fluidd - v1.23.0 
klipper - v0.11.0-65-gbca2671e 
moonraker - v0.7.1-805-gc9a1d0f 
z_calibration -  v0.9.2-0-gf212b40

**Comment by Arakon** [comment]
I can confirm this issue, it has happened multiple times to me on two different PCs, both with firefox, across the past years (and versions, obviously), and across two different printers.
Running on Raspberry Pi 3B and Raspberry Zero 2 W.

**Comment by pedrolamas** [comment]
I have no idea if your issue is related, but if you are connecting via WiFi, you might want to try installing [Sonar](https://github.com/mainsail-crew/sonar) and see if that helps with the problem.

**Comment by pedrolamas** [comment]
I believe this has been fixed in the most recent Fluidd releases, so closing the ticket as such.
