### ISSUE TITLE
Instant (sort of live) speed update for tool head movement 

### ISSUE THREAD

**Issue by dhruvinsh** [fluidd-core/fluidd#1018]
### Is your feature request related to a problem? Please describe

NA

### Describe the solution you'd like

We have filament flow Measurement but missing the speed for tool head movement. 

While we have co-ordinates updates present, Pedro suggested over discord that its easy to display on dashboard.

**Comment by pedrolamas** [comment]
@dhruvinsh thanks for creating this Feature Request!

Would something like this work for you?

![image](https://user-images.githubusercontent.com/85504/215056718-6d7fe08b-006c-4718-b43c-0929e5f2e734.png)

Using the same style as in the live coordinates, we would just add the live speed to the "Speed" label, as shown on the above image

**Comment by dhruvinsh** [comment]
@pedrolamas  that look really nice. Easy to read and placement also looks good. 

Although, having the tool head speed and flow rate together, would that make sense? Just an opinion. Else current implementation looks good.
