### ISSUE TITLE
Fluidd not properly url-encoding "%" in filenames

### ISSUE THREAD

**Issue by gwillmer** [fluidd-core/fluidd#1023]
### Fluidd Version

1.23.0

### Browser

Chrome

### Device

Desktop PC

### Operating System

Windows

### What happened

Trying to edit or Gcode preview a file with a "%" in the filename results in a "400 Bad Request" error.

### What did you expect to happen

Editor or Gcode preview appears

### How to reproduce

Rename a file in the jobs list, add a "%", then attempt to edit or preview.

Attempting to edit a file from the configuration tab results in the same behavior.

### Additional information

Fluidd is not properly url-encoding the "%" in filenames.

For a file named "test 35% if.gcode", fluidd makes a request for

http://[fluidd]/server/files/gcodes/test%2035%%20if.gcode

instead of

http://[fluidd]/server/files/gcodes/test%2035%**25**%20if.gcode

**Comment by pedrolamas** [comment]
@gwillmer Thanks for reporting this issue, I've checked and confirmed the problem and we will make sure this is fixed for the next release.
