### ISSUE TITLE
Unable to set tool extrude length > 50mm

### ISSUE THREAD

**Issue by thijstriemstra** [fluidd-core/fluidd#1032]
### Fluidd Version

1.23.1

### Browser

Firefox

### Device

Desktop PC

### Operating System

Windows

### What happened

In the system settings it's possible to change the default extrude length to a 100mm.

![Capture](https://user-images.githubusercontent.com/305679/217648581-3ae3dd0a-2247-47ef-9224-1ad1b31deea9.JPG)

But this screws up the tool interface on the dashboard and it seems like it won't allow higher than 50 there?

![Capture2](https://user-images.githubusercontent.com/305679/217648710-11a6d4aa-5cae-4b82-a9f2-9d7f93552ad4.JPG)

### What did you expect to happen

Being able to use > 50mm extrude length

### How to reproduce

Try to set to > 50 extrude length in tool interface on dashboard.

**Comment by thijstriemstra** [comment]
I see, thanks @pedrolamas! In that case the system settings panel shouldn't allow more than `max_extrude_only_distance` right (and right now it does)?

**Comment by pedrolamas** [comment]
That's a very fair point, and yes, I believe there is a bug there (even if we allow to enter a setting over the Klipper limit, the interface should not use that).
