### ISSUE TITLE
Finish date-time in the PRINTING section does not respect the configured date format

### ISSUE THREAD

**Issue by Anathema-Device** [fluidd-core/fluidd#1058]
<img width="698" alt="Tronxy_DELL___Dashboard" src="https://user-images.githubusercontent.com/36930217/223582522-eef7f862-57f5-4976-8bf0-7232748a4291.png">
### Fluidd Version

1.23.2  (the current version at this time)

### Browser

Firefox, Other (Please tell us below)

### Device

Desktop PC

### Operating System

Windows, macOS

### What happened

I have both the date and time formats set to ISO8601.  Today is 2023.03.07 the finish time shown for the current print is displayed as "08/03 01:48" which I would interpret as MM/DD HH:MM.  In the case of ISO8601 I would expect it to be "03/08 01:48"  (tomorrow morning at 1:48 AM).  So it looks like the Finish time is being displayed using the locale time format not the configured time format, if that makes sense.

### What did you expect to happen

I expect to see the Finish time formatted according to the date and time formats chosen in the fluidd settings.  In this case as MM/DD HH:MM.

### How to reproduce

Configure the date & time formats to be ISO8601 then start a print and observe the Finish time in the PRINTING section

### Additional information

Thanks for the great work, I really enjoy fluidd !

**Comment by Anathema-Device** [comment]
Thank you for looking at this. Maybe it is a bug in Javascript?   When I look at the 8061 stuff it sez "the order of the elements used to express date and time in ISO 8601 is as follows: year, month, day, hour, minutes, seconds, and milliseconds."  So it does not say that if the year is not presented then the order would change.  It would not be terrible to present the year there too as it is conceivable that a print started at the end of one year would finish in the next.  Very small but interesting problem though ;)

**Comment by pedrolamas** [comment]
> Maybe it is a bug in Javascript?

Not actually a bug as `Date.prototype.toLocaleDateString()` just doesn't have any support for ISO-8601, only real locales...

We were trying to "fake it" by using "sv-SE" as the closest locale matching ISO-8601... till you notice that it also failed on that particular case! 😁

It seems using "lt" locale is a closer match and fixes the issue you pointed out, so we will be using that one going forward!
