### ISSUE TITLE
"Are you sure? This will delete all files and folders." for job delete

### ISSUE THREAD

**Issue by sprior** [fluidd-core/fluidd#1080]
### Fluidd Version

1.23.4

### Browser

Firefox

### Device

Laptop

### Operating System

Linux

### What happened

When I click on a file in the jobs list and select remove the dialog that comes up is "Are you sure? This will delete all files and folders."

### What did you expect to happen

I would suggest that this makes it sound like a bulk operation that's going to wipe a lot of data instead of just removing that one thing you asked it to remove.  I would suggest changing that message to confirming that the selected job will be removed.

### How to reproduce

Click an item in jobs and select remove.

**Comment by jaarenhoevel** [comment]
This also applies to files in the configuration editor.
