### ISSUE TITLE
Missing tooltips

### ISSUE THREAD

**Issue by thijstriemstra** [fluidd-core/fluidd#1090]
### Fluidd Version

1.23

### Browser

Firefox

### Device

Desktop PC

### Operating System

Windows

### What happened

Missing tooltips on buttons outlined with a red border in images below:

![Capture](https://user-images.githubusercontent.com/305679/234443111-7780c454-2d8e-408c-bce8-0db76f779e9d.JPG)

![Capture2](https://user-images.githubusercontent.com/305679/234443135-2c0b455d-22df-4407-86cd-8fab1b1485e2.JPG)

![Capture](https://user-images.githubusercontent.com/305679/234453909-5ad8fdad-5fd1-4712-8c38-b4edb0de5e57.JPG)

### What did you expect to happen

A tooltip when rolling over the button with mouse cursor, like the other btns on the page do.

### How to reproduce

Use mouse to rollover buttons with missing tooltips.

**Comment by pedrolamas** [comment]
I've added the missing File Browser button tooltips, but the window ones might soon change, so will leave that as is for now.
