### ISSUE TITLE
Add an Option to open setting files folded

### ISSUE THREAD

**Issue by XoBoR** [fluidd-core/fluidd#1092]
### Is your feature request related to a problem? Please describe

When I open a .cfg file in the Editor, i almost always instinctively hit "fold all" to navigate the file and get a overview. In case anybody doesn't know this very usefull feature, it gets you from this: 
![image](https://user-images.githubusercontent.com/38147819/235084429-004fdcff-cde1-4b0d-91c1-a3cbd47b7ac3.png)

to this: 
![image](https://user-images.githubusercontent.com/38147819/235084641-ac130bbf-a6c5-4fae-84d1-bbf86148ca07.png)

### Describe the solution you'd like

I would like a little Option in the File Editor section to open cfg files with all sections folded.

### Describe alternatives you've considered

Alternatively an even better approach would be to store the "fold state" between multiple openings of the same file, but that is probably considerably more effort.

**Comment by pedrolamas** [comment]
Hi @XoBoR thank you for opening this Feature Request!

So far, I haven't found a proper way to force a file to open with ranges collapsed...

However, I am looking into storing the current state of the regions, so when one opens the same file again, it will have the same collapsed regions!

I still need to evaluate this further, but I believe this might be a good compromise for the problem, so you will be able to manually call "collapse all regions" and the editor would remember that the next time you opened the same file.

**Comment by XoBoR** [comment]
> Hi @XoBoR thank you for opening this Feature Request!
> 
> So far, I haven't found a proper way to force a file to open with ranges collapsed...
> 
> However, I am looking into storing the current state of the regions, so when one opens the same file again, it will have the same collapsed regions!
> 
> I still need to evaluate this further, but I believe this might be a good compromise for the problem, so you will be able to manually call "collapse all regions" and the editor would remember that the next time you opened the same file.

Hi @pedrolamas thanks a lot for looking into it! Storing the collapsed state of the regions indeed sounds like the best solution, and it is  what most modern IDEs do too I think. I just thought that blindly collapsing everything could be "good" enough and seemed to be either to implement.

Thanks again for everything, cheers!
