### ISSUE TITLE
Toolhead movement via virtual joystick

### ISSUE THREAD

**Issue by MeishuH** [fluidd-core/fluidd#1103]
### Is your feature request related to a problem? Please describe

it is not convenient to move the tool head via the buttons.. takes too long and it is not easy to reach the rand.  it 

### Describe the solution you'd like

implement a small virtual joystick as a movement alternative.  it could be pressed with the mouse button and when the mouse moves, the tool head would move in the same direction... as long as the button is pressed. 
Speed of the movement could be dependent on the distance btw the mouse cursor and the center of the joystick.  

### Describe alternatives you've considered

do it as mainsail...  

### Additional information
I   am aware it is not that simple..   the boundaries of the printer need to be taken into account,  so it can stop on the max position.   Furthermore,  if this has to be written in  GCode,  it could be  ...  not a fluid movement..  perhaps  .. I guess
_No response_

**Comment by pedrolamas** [comment]
Hi @MeishuH, thank you for opening this Feature Request.

I've taken some thought to this and the main issue I see is that the movements would not be fluidd at all as Klipper would not be able to properly plan for them (we would be sending a lot of commands for this to work, and some weird jerking would eventually happen)

We would require something else implemented in Klipper to make this work smoothly, but I have my reservations that it will make Klipper mainline (truth be told, it is not exactly a core feature), so I will close this for now but please feel free to reopen if things do change.
