### ISSUE TITLE
"Unable to open file" when the file contains an accent

### ISSUE THREAD

**Issue by TheQuentincc** [fluidd-core/fluidd#1120]
### Fluidd Version

1.18 and 1.24

### Browser

Edge

### Device

Desktop PC

### Operating System

Windows

### What happened

My gcode file had an accent "è" in it's name and when trying to print it, it just said it was unable to open the file. I tried the same gcode without accent in it's filename and it was working.

### What did you expect to happen

I expect a message that tells "filename is not supported" instead of "unable to open file"

### How to reproduce

Upload a gcode file with an accent in it's filename, in my case an "è".

**Comment by pedrolamas** [comment]
This is not something we should fix in Fluidd as users can upload files bypassing Fluidd interface (using other interfaces, ssh, scp, etc.) and would still experience this problem.

Nevertheless, this is a known issue with Klipper when using Python 2: Python 2 does not handle non-ascii characters correctly, so this would happen.

Python 3 is now recommended for Klipper, so your best way forward to fix this issue would be to reinstall Klipper with Python 3.
