### ISSUE TITLE
Simplify translation process with Weblate

### ISSUE THREAD

**Issue by Daviteusz** [fluidd-core/fluidd#1136]
### Is your feature request related to a problem? Please describe

Translators are not developers and may have trouble using the current translation method (vscode with addon or babeledit) They may even have problems with github usage.

### Describe the solution you'd like

I use self-hosted Weblate for translation. It has a very convenient gui, you can set various flags, for example, mark untranslatable words or characters that you can click on and they will be automatically filled in the translation field.

Changes can be sent automatically e.g. every 24h as PR or as commit. Commit descriptions or PR names can be managed by the project author, not the translator. The translator can simply focus on the translation.

I've been using this solution for a few months now and overall I haven't experienced any problems. 

### Additional information

<img src=https://github.com/fluidd-core/fluidd/assets/11527277/07ffe6f2-16e2-40fd-9e29-1b57507e753d width=50%><img src=https://github.com/fluidd-core/fluidd/assets/11527277/813b49d0-6bdb-416e-9e0d-318d41eada11 width=50%><img src=https://github.com/fluidd-core/fluidd/assets/11527277/ad02b37d-ebbc-4dc4-9f33-526297c4b1f1 width=50%><img src=https://github.com/fluidd-core/fluidd/assets/11527277/aad26265-4efb-49dd-a753-c4426e2b70ec width=50%>

**Comment by Daviteusz** [comment]
Pull request #1164 has appeared, so...

**Comment by pedrolamas** [comment]
Thanks @Daviteusz but it's not a done deal yet... we are still trying to get Fluidd licensed as a Libre project!

**Comment by Daviteusz** [comment]
Closing due to #1239
