### ISSUE TITLE
Incorporation of Moonraker [sensor]

### ISSUE THREAD

**Issue by JamesH1978** [fluidd-core/fluidd#1137]
### Is your feature request related to a problem? Please describe

Moonraker has the ability to register sensors from other devices via MQTT and other methods,

### Describe the solution you'd like

 It would be nice to see these in the Fluidd interface

**Comment by pedrolamas** [comment]
I've taken a quick look at this, I guess the main question from me is how we are to present dynamic data...

Users can use `set_result` to pass not only temperature, pressure, humidity (all measurements that Fluidd can already show on the temperature chart), but also any other key they could want (like power, energy, etc.)

We might need to use some table/tree view to show the values from these extra sensors!

**Comment by bartwaw** [comment]
but can't be done like this: total watts used by print job, and then store it in some log. I'm not best in programming

**Comment by JamesH1978** [comment]
Fkuidd has no log, everything it can store at the moment is held in the moonraker database, which would be up to that project to implement first

**Comment by bartwaw** [comment]
So as i understand for example  "Print duration" is stored in moonraker ?

**Comment by midnight1979** [comment]
> @bartwaw adding to history will probably not be possible, as that would require Moonraker to store history on that side first!
> 
> If we did that on Fluidd only, once you close the tab or refresh it, all the history data would be cleared!

As I know now moonracker having this feature and store sensor values history. Does it possible to add these values to chart?
