### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [fluidd-core/fluidd#1153]
### Fluidd Version

All

### Browser

Other (Please tell us below)

### Device

Desktop PC, Other (Please tell us below)

### Operating System

Other (Please tell us below)

### What happened

https://hosted.weblate.org/projects/fluidd/fluidd/#information
says AGPLv3-only, whereas https://github.com/fluidd-core/fluidd/blob/develop/LICENSE says GPLv3

### What did you expect to happen

I think changing to GPLv3-or-later is better, as it is compatible, and allows for the most flexibility

### How to reproduce

https://www.gnu.org/licenses/license-list.html#AGPLv3.0 It is also technically not compatible with GPLv3 in a strict sense: you cannot take code released under the GNU AGPL and convey or modify it however you like under the terms of GPLv3, or vice versa. 

### Additional information
It  can be changed in
https://hosted.weblate.org/settings/fluidd/fluidd/
and
https://hosted.weblate.org/settings/fluidd/glossary

**Comment by matmen** [comment]
Thanks for the heads up, this should be fixed now :)
