### ISSUE TITLE
Macros/Webhooks

### ISSUE THREAD

**Issue by maartinhansen** [fluidd-core/fluidd#1156]
### Is your feature request related to a problem? Please describe

No problem. But I'd like to make some shortcuts, in reality just having macros available in an URL. 

### Describe the solution you'd like

Somehow making macros start by URL like 192.168.1.XXX/Macro/STOP_PRINT.

### Additional information

This is really all due to my love for automation, like iOS Shortcuts or a streamdeck. Getting access to a semi-advanced feature like this through just the touch of a button? Pheeew. Sound fantastic in my world!

**Comment by pedrolamas** [comment]
Hi @maartinhansen thanks for opening this Feature Request.

Fluidd is just a web frontend, so those type of changes need to be requested to Moonraker (the API server)

Having said that, that functionality is already provided by Moonraker: https://moonraker.readthedocs.io/en/latest/web_api/#run-a-gcode
