### ISSUE TITLE
Homing button for X, Y and Z disappeared after mostly HW changes

### ISSUE THREAD

**Issue by ValerioMalara** [fluidd-core/fluidd#1174]
### Fluidd Version

v1.25.3

### Browser

Chrome

### Device

Desktop PC

### Operating System

Windows

### What happened

After i've done some upgrades on my printer (FLSUN SR) the homing buttons for the separate axes have disappeared, only the XY one remains. Homing works perfectly fine using G28 even on the separate axis. Following the modifications I've done:

-reflashed the firmware to switch to UART1 as connection interface
-removed the filament run out sensor
-changed the extruder
-changed hotend and thermistor

I've seen an old report about a similar bug regarding homing macro but I have nothing like that.

### What did you expect to happen

Homing buttons rendered correctly

### How to reproduce

Unknown

**Comment by pedrolamas** [comment]
Hi @ValerioMalara thank you for reporting this.

The FLSUN SR is a delta printer, which means homing can only be done on every axis at the same time (as far as I know, there is no way to separately home the axis on a delta printer).

Having said that, I see now there is an issue where the only home button that should be there is the "All", not the "XY" one...
