### ISSUE TITLE
The tool change UI does not work if the commands are not macros

### ISSUE THREAD

**Issue by viesturz** [fluidd-core/fluidd#1195]
### Fluidd Version

V1.25.3

### Browser

Chrome

### Device

Desktop PC

### Operating System

Windows

### What happened

The tools display only works when the T1, T2... commands are gcode macros 
Of they are python extensions, they are not detected by Fluidd.

### What did you expect to happen

The tool buttons should detect the presence of a TN command and should not 
rely if it's implemented as macro or not.

### How to reproduce

Install https://github.com/viesturz/klipper-toolchanger
And configure some tools.

There might be other tool changing extensions that are affected as well.

**Comment by pedrolamas** [comment]
Thanks for opening this @viesturz.

As previously discussed in #1123, we do not support non-mainland Klipper or Moonraker features such as the specific toolchanger module you referenced.

As such, I have changed the status of this ticket from Bug to Feature Request.
