### ISSUE TITLE
Support opening Gcode files in Gcode Preview with drag&drop

### ISSUE THREAD

**Issue by MarSoft** [fluidd-core/fluidd#1202]
### Is your feature request related to a problem? Please describe

The File Manager component supports drag&drop feature. It can be used to move files around or to enqueue a file by dragging it to `Job Queue` block.
But if I drag the file to `Gcode Preview` window, nothing happens.
It would be nice to be able to drag the file over `Gcode Preivew` and preview it right away.

Also, I'd like to be able to drag the file to some external website, for example [Pretty Gcode](https://github.com/Kragrathea/pgcode) which can also be embedded as a "camera", and have this file opened on the site. For it to work, we should include a file's URL with the drag event.

### Describe the solution you'd like

For the first part, I'm not sure how is it to better implement.
For the 2nd part, we would add the code here: https://github.com/fluidd-core/fluidd/blob/35667236da00a40fe36c60845ca8db40923e24d0/src/components/widgets/filesystem/FileSystemBrowser.vue#L447-L461
with a call to `e.dataTransfer.setData('text', full_url_to_the_file)`. I've checked and file can be downloaded by its full URL; such URL looks something like `http://MOONRAKER_IP_OR_DOMAIN:PORT/server/files/gcodes/FILEPATH`. Not sure what would be the best way to generate such URL.

### Additional information

The `PrettyGcode` should also be updated to accept HTTP links as input files in addition to local files, but it would be easy as soon as we attach the actual URL in the event, instead of just storing current object in a private variable.

**Comment by pedrolamas** [comment]
This has now been implemented from Fluidd's side, so that you can drag a job (or any other file) from the file browser window and it will supply the drop target with a download link to the dragged file.
