### ISSUE TITLE
When a URL including a path is specified, fluidd dispatches requests to / anyway.

### ISSUE THREAD

**Issue by Laikulo** [fluidd-core/fluidd#1203]
### Fluidd Version

v1.25.2-e06c7ad

### Browser

Firefox, Other (Please tell us below) (Chromium embeded into OrcaSlicer)

### Device

Desktop PC, Laptop, Mobile device (Phone, Tablet or similar)

### Operating System

Windows, Linux, Android

### What happened

When a moonraker url in the form `http://printhost.example.net/printer1/` is provided, the URL is accepted, but requests to the moonraker API are dispatched to `http://printhost.example.net/ACTION`

URL is accepted:
![image](https://github.com/fluidd-core/fluidd/assets/2963965/6222c388-72d3-4534-aa15-245e01351798)

First load:
![image](https://github.com/fluidd-core/fluidd/assets/2963965/6091f94b-cf34-4797-afee-09a785903acc)

Requests going to root of host:
![image](https://github.com/fluidd-core/fluidd/assets/2963965/6fee82c8-5b75-449b-bab8-06eefb5cdc0e)

Behavior on a refresh

### What did you expect to happen

Requests to be dispatched to `http://printerhost.example.net/printer1/ACTION`

### How to reproduce

Given an print host with hostname printhost.example.net:
With moonraker ae1d3b039308a84cbc01092f11b4c7c3b84da138 or later serving on localhost:8080, configure route_prefix to "moonraker1"
Configure an httpd listening on 80 that reverse proxies /moonraker1 to localhost:8080, with websockets enabeled.
Configure the httpd to serve fluidd's htdocs for other requests.

Navgate to `http://printhost.example.net`
In the "add printer" dialogue that appears, enter `http://printhost.example.net/moonraker/`

**Comment by pedrolamas** [comment]
HI @Laikulo thanks for opening this ticket.

The "route_prefix" setting is a recent Moonraker feature, hence why we do not support it yet. As such I've changed this ticket classification from Bug to Feature Request.

We will look into this as soon as possible!

**Comment by Laikulo** [comment]
Can confirm that this now works as expected!
