### ISSUE TITLE
When building with `--base` config.json is still requested from /

### ISSUE THREAD

**Issue by Laikulo** [fluidd-core/fluidd#1206]
### Fluidd Version

gca3abf34

### Browser

Firefox

### Device

Laptop

### Operating System

Linux

### What happened

After building fluid with `npm run build -- --base=/fluidd/` and installing the resultant dist at /fluidd/ on an httpd, fluidd failed to load.
Investigation determined that fluidd was requesting config.json from /.

Workaround: Configure httpd to respond to /config.json with the file at /fluidd/config.json

### What did you expect to happen

Fluidd should request the config bundle from the base url if one is specified.

### How to reproduce

1. `npm ci`
2. `npm run build -- --base=/fluidd/`
3. `cp dist/* -r /srv/www/htdocs/fluidd`
4. `firefox http://localhost/fluidd/`

**Comment by pedrolamas** [comment]
#1207 partially fixed this, as in it will allow building with the `--base` parameter, and the app should be usable.

However, the service worker will not work correctly as the default `generateSW` strategy requires all paths to account to the `base` path change (it does not automatically change those) and changing to `injectManifest` will open a can of worm that at the moment I don't think it is worth it as this is an unsupported scenario for us (hence why you had to build it manually!)
