### ISSUE TITLE
Seeing "priešpiet" with English

### ISSUE THREAD

**Issue by Majawat** [fluidd-core/fluidd#1220]
### Fluidd Version

v1.26.1-62acc09

### Browser

Chrome

### Device

Desktop PC, Mobile device (Phone, Tablet or similar)

### Operating System

Windows, Android

### What happened

While using English as a display language, it often shows "priešpiet" instead of something like "pm".
![image](https://github.com/fluidd-core/fluidd/assets/12058855/6ab9a9eb-dff3-4065-b8e1-ee0526f40ed3)

### What did you expect to happen

Should show "pm" instead.

### How to reproduce

Brand new install of Klipper/Moonraker/Fluidd, set Display Language to English, start a job.

### Additional information

I've seen it other places, but can't pinpoint where at the moment.

**Comment by pedrolamas** [comment]
Hi @Majawat, thank you for reporting this issue.

Can you please post a screenshot of your Fluidd General Settings? Specifically, I am interested in the Date and Time formats that you have currently selected.

**Comment by Majawat** [comment]
![Screenshot_20231030-124333](https://github.com/fluidd-core/fluidd/assets/12058855/916a28a6-48cc-4d65-9937-ef11a3cafd76)
