### ISSUE TITLE
Broken mesh

### ISSUE THREAD

**Issue by digitalninja-ro** [fluidd-core/fluidd#1234]
### Fluidd Version

1.26.2

### Browser

Firefox, Safari, Chrome

### Device

Desktop PC, Laptop

### Operating System

macOS

### What happened

The mesh is a mess. But only on fluidd. I have also installed MainSail  on the same pi3 and everything seem to work perfect. 

Same mash on:
Fluidd
<img width="864" alt="image" src="https://github.com/fluidd-core/fluidd/assets/79784628/2ab0a1f1-9d87-465a-b74e-c10f8c4db39d">
MainSail
<img width="768" alt="image" src="https://github.com/fluidd-core/fluidd/assets/79784628/da5a963a-811c-4dc0-850c-8b227b60c014">

This is happen for me with the last version of fluidd 1.26.2
<img width="756" alt="image" src="https://github.com/fluidd-core/fluidd/assets/79784628/b7fb87f2-ddb8-4266-b9df-e59bc2c51583">

### What did you expect to happen

Smooth mesh

### How to reproduce

I don't know how to reproduce.

**Comment by pedrolamas** [comment]
Hi @digitalninja-ro, thank you for opening this issue.

Can I ask that you please upload a klippy.log from the printer where this is happening?

**Comment by digitalninja-ro** [comment]
Hi @pedrolamas thank you for the quick answer. Here is my klippy.log
[klippy.log](https://github.com/fluidd-core/fluidd/files/13325064/klippy.log)
