### ISSUE TITLE
Cannot remove default "Part fan"

### ISSUE THREAD

**Issue by thijstriemstra** [fluidd-core/fluidd#1280]
### Fluidd Version

1.27

### Browser

Firefox

### Device

Desktop PC

### Operating System

Windows, macOS

### What happened

I defined the following 2 fans:

```
## FAN1 on CANBUS EXT1
[fan_generic fan_12v]
pin: ext1:PA0
kick_start_time: 0.5
##  Depending on your fan, you may need to increase this value
##  if your fan will not start. Can change cycle_time (increase)
##  if your fan is not able to slow down effectively
off_below: 0.10

## FAN2 on CANBUS EXT1
[fan_generic fan_24v]
pin: ext1:PA1
```

But after refreshing/clearing browser cache I still see the "default" `Part fan` listed in the GUI:

![afbeelding](https://github.com/fluidd-core/fluidd/assets/305679/59171fd3-f50e-4552-ad0a-09e7bed2cf61)

The `Part fan` controls (obviously) don't do anything though.

### What did you expect to happen

Ability to remove the `Part fan`.

### How to reproduce

Use an empty `printer.cfg` with bare minimum except for any fans, it'll still show the `Part fan`.

**Comment by pedrolamas** [comment]
Not entirelly sure, but we have the part fan "hard coded", proabably some old code!

We will remove it for next release.
