### ISSUE TITLE
Toolhead distance not updating correctly

### ISSUE THREAD

**Issue by thijstriemstra** [fluidd-core/fluidd#1285]
### Fluidd Version

1.27

### Browser

Firefox

### Device

Desktop PC

### Operating System

Windows, macOS

### What happened

I defined following distances:

![tool3](https://github.com/fluidd-core/fluidd/assets/305679/c3f5a601-fa29-4ff7-ad55-4410b07b58d2)

Switching back to dashboard shows incorrect values:

![tool1](https://github.com/fluidd-core/fluidd/assets/305679/f5934eef-4b66-407b-8ab3-ba6bd06c7c44)

Clicking one of them renders values correctly:

![tool2](https://github.com/fluidd-core/fluidd/assets/305679/1cdbcb5a-5b15-4361-9074-9ae65f3eda7c)

### What did you expect to happen

Display correct values.

### How to reproduce

See above.

**Comment by pedrolamas** [comment]
Hi @thijstriemstra, thanks for opening this issue.

I am aware of this behavior (truth be told, we coded it like that), and it is due to the fact that if the user removes the current distance value from the available ones, we are adding it back as a temporary one, that will disappear once the user picks one from the list.

Granted, this behavior is quite weird, and I am will be happy to change it (probably will just pick the smallest from the available list in those cases)

**Comment by thijstriemstra** [comment]
> Granted, this behavior is quite weird, 

Yea, when I click 500 in above example, it will switch to the new button layout, and select 250 instead (because of the re-ordering or something), making me have to click 500 again in order to properly select it.

**Comment by thijstriemstra** [comment]
A side note; the max distances that can be defined is 6, any chance this could be arbitrary?

**Comment by pedrolamas** [comment]
We limited the number of values as we know that it can screw the layout of the page.

**Comment by thijstriemstra** [comment]
>  it can screw the layout of the page.

I see, but I would honestly don't care, it's the functionality I'm after..

**Comment by pedrolamas** [comment]
I assume that when you removed the `1` from the list, the "Default toolhead move length" went blank (which is because the value previously selected got removed)

![image](https://github.com/fluidd-core/fluidd/assets/85504/ceb1013d-53d6-43a7-82a6-d116adfca5d0)

Does this match what you are seeing?

**Comment by thijstriemstra** [comment]
Ah yes, it appears to be blank:

![afbeelding](https://github.com/fluidd-core/fluidd/assets/305679/27988883-ba74-4ae8-bf41-2b888ca7e675)
