### ISSUE TITLE
Language commit history incorrect

### ISSUE THREAD

**Issue by thijstriemstra** [fluidd-core/fluidd#1293]
### Fluidd Version

1.27.1

### Browser

Firefox

### Device

Desktop PC

### Operating System

Windows

### What happened

Language is set to English:

![afbeelding](https://github.com/fluidd-core/fluidd/assets/305679/9a0ad997-93fe-4412-b66c-3b01c7015e1e)

But I'm seeing Dutch in the commit history panel (`gisteren` and `eergisteren`):

![afbeelding](https://github.com/fluidd-core/fluidd/assets/305679/f47c8215-75f0-43d8-a368-33efd4a54f71)

### What did you expect to happen

Honour language setting and ignore browser/os language.

### How to reproduce

Use a non-english browser to view commit history.

**Comment by pedrolamas** [comment]
Hi @thijstriemstra, thanks for opening this issue.

Can you check if changing to another language and then back to English solves the problem?

**Comment by thijstriemstra** [comment]
I'll have to check once moonraker or klipper has an update again, can't access panel without updates.

**Comment by thijstriemstra** [comment]
>  changing to another language and then back to English solves the problem?

- changed to german
- checked (still dutch)
- changed to english
- checked (still dutch)

**Comment by pedrolamas** [comment]
Can you try opening in an anonymous browser window? 

If it shows with no problem on the anonymous window, I recommend that performing a full refresh of Fluidd (clearing the browser cache)

**Comment by thijstriemstra** [comment]
>  (clearing the browser cache)

I'm doing that everytime already. 

> Can you try opening in an anonymous browser window?

Yep but will have to wait for klipper/moonraker updates again first, since I just updated 😋

**Comment by thijstriemstra** [comment]
Tested again, and a private firefox window didn't make a difference.

**Comment by pedrolamas** [comment]
I might know what is at play here, let me do some checks and I will report back when I can...

**Comment by pedrolamas** [comment]
I did a quick test on this and now I recall that we are using the browser locale to format dates & times, so I assume your main browser language is Dutch?

**Comment by thijstriemstra** [comment]
yea it's dutch
