### ISSUE TITLE
Fluiddpi asking to add printer when only one printer

### ISSUE THREAD

**Issue by samisanerd1** [fluidd-core/fluidd#1294]
### Fluidd Version

1.19.0

### Browser

Chrome

### Device

Desktop PC

### Operating System

Windows

### What happened

i have had my ender 3 v2 and raspi 4 setup for a month now. it was working great until, right after i install the sprite pro direct drive extruder, the thing does this. i have no idea what to do i'm not sure how to change my config files, because it only shows ![Screenshot 2023-12-25 221553](https://github.com/fluidd-core/fluidd/assets/143911085/834a5f68-ab64-4057-a868-df9e8bb4b899)

### What did you expect to happen

The ui to open and for me to access my printer

### How to reproduce

Im not sure. it just happened

**Comment by pedrolamas** [comment]
Hi @samisanerd1, from your message on Klipper Discord I see that you have found and fixed this problem, so I am closing this now.

**Comment by samisanerd1** [comment]
I didnt message any discord, but i did manage to fix it by reinstalling everything.

**Comment by pedrolamas** [comment]
My apologies @samisanerd1 , somehow I saw a very similar screenshot in Discord today and for a moment thought it was from the same user.
