### ISSUE TITLE
Repo is corrupt

### ISSUE THREAD

**Issue by thijstriemstra** [fluidd-core/fluidd#1295]
### Fluidd Version

1.27.1

### Browser

Firefox

### Device

Desktop PC

### Operating System

Windows

### What happened

I'm seeing this in the update screen:

![afbeelding](https://github.com/fluidd-core/fluidd/assets/305679/d8b33ffd-6319-4619-bf4c-5d086f7fb6f9)

the `Repo is corrupt` message starting showing up today.. These are pristine clones of the official klipper/moonraker repos.

### What did you expect to happen

Not see a warning message.

### How to reproduce

-

**Comment by pedrolamas** [comment]
Hi @thijstriemstra, those details are provided by Moonraker, all Fluidd does is present the status as it gets it.

Your moonraker.log should have some information about what happened (probably some git error messages there)

**Comment by thijstriemstra** [comment]
I rebooted everything and checked  moonraker logs:

```
tail -f -n 100 printer_data/logs/moonraker.log
```

But no errors and UI also seems to be fixed now.. weird? I'll close it for now and re-open when I see it again.

**Comment by thijstriemstra** [comment]
What are the conditions for that `Repo is corrupt` warning to show up btw?

**Comment by pedrolamas** [comment]
Only condition from Fluidd perspective is for Moonraker to report the repos as corrupt.

I'm not entirely sure what conditions does Moonraker have to consider the repo corrupt.
