### ISSUE TITLE
Live speed is missing from Fluidd

### ISSUE THREAD

**Issue by RenanAz** [fluidd-core/fluidd#1304]
### Fluidd Version

1.27.1

### Browser

Chrome

### Device

Desktop PC

### Operating System

Windows

### What happened

The Live speed feature (added here [)](https://github.com/fluidd-core/fluidd/pull/1019) is now missing from below the live coordinates. 
![image](https://github.com/fluidd-core/fluidd/assets/41326816/8665f916-91db-456e-bf42-1869ee4d4029)

### What did you expect to happen

Expect to see the live printing speed as it was in the past releases.

### How to reproduce

Start a print and observe below the live coordinates.

**Comment by RenanAz** [comment]
Ah ok, it makes sense. Thank you!
Just out of curiosity, was this in the release notes and I missed it? I did try to search for it before. 
Thanks again for your awesome support.

**Comment by pedrolamas** [comment]
It was the "improves estimates calculation" (granted, not very explicit to what we actually did there!) https://github.com/fluidd-core/fluidd/pull/1283
