### ISSUE TITLE
[GCode Preview] 'Show Parts' toggle should be off by default for gcodes with only one part

### ISSUE THREAD

**Issue by rursache** [fluidd-core/fluidd#1308]
### Is your feature request related to a problem? Please describe

99% of the time I only print once piece at a time. It's annoying to manually disable 'Show Parts' toggle everytime as the GCode Preview gets cluttered with the blue border and the cancel symbol in the middle.

### Describe the solution you'd like

For gcode files containing only one object, its of no use to have the "Show Parts" on by default. Canceling the only part out of printing from a single object gcode file is equal to just canceling the print itself

### Describe alternatives you've considered

--

### Additional information

> [!NOTE]
> Please note that even though it seems like there are 3 objects, they are actually merged from the slicer

Here is how GCode Preview looks by default when printing a gcode containing one single model:
<img width="508" alt="1" src="https://github.com/fluidd-core/fluidd/assets/3800336/02b3dd99-bb0d-4765-8251-19827d04f4cd">

Here is how it should look by default ("Show Parts" off):
<img width="512" alt="2" src="https://github.com/fluidd-core/fluidd/assets/3800336/4c63a585-908a-4908-9476-9135a0faf15a">

**Comment by matmen** [comment]
I don't think the bounding boxes are useless for single parts, they still show the max size of the object. Nonetheless, I've created a PR for this: https://github.com/fluidd-core/fluidd/pull/1310
