### ISSUE TITLE
Spoolman: Select fields shown in Fluidd

### ISSUE THREAD

**Issue by oRudi07** [fluidd-core/fluidd#1336]
### Is your feature request related to a problem? Please describe

Is there any way to select the options from Spoolman that are shown in Fluidd?
eg i do not need the fields like charge, comment or location shown in Fluidd.
But I do not find the option to select the fields that are shown.
Anybody who can help me?
Greetings

### Describe the solution you'd like

no solution

**Comment by matmen** [comment]
Thanks for your request. Fluidd currently doesn't have an option to select the columns shown in the spool selection modal.
Which additional columns were you looking for specifically?
