### ISSUE TITLE
Change Configuration Reference Page Based on Klipper forks

### ISSUE THREAD

**Issue by Kizime123** [fluidd-core/fluidd#1349]
### Is your feature request related to a problem? Please describe

I currently use dangerklipper for all my klipper needs,  it's a bit more of an inconvenience to find configuration reference details since I often will click the configuration reference button. This leads me to realize I have to actually go into the dangerklipper github for the proper configuration reference.

### Describe the solution you'd like

Whenever someone is using a klipper fork instead of referencing the stock klipper configuration reference page (https://www.klipper3d.org/Config_Reference.html), reference the forks configuration reference page.

**Comment by pedrolamas** [comment]
Hi @Kizime123, thank you for submitting this Feature Request.

I have taken a quick look at this, and my first thought is that we can't perform any "automatic" discovery just by looking at the fork the user has (there is no guarantee that the docs from said fork have been published!), so manual (user) indication is indeed required here, probably via an optional setting in Fluidd.

**Comment by Kizime123** [comment]
@pedrolamas This change would make alot of sense. Knowing docs might not be updated instead a setting to allow you to manually enter it would make sense! Could it be possible to potentially have the fork actually set this information too on some sort of input too?
