### ISSUE TITLE
Spoolman title bar incorrectly rendering

### ISSUE THREAD

**Issue by thijstriemstra** [fluidd-core/fluidd#1351]
### Fluidd Version

1.28

### Browser

Firefox

### Device

Desktop PC

### Operating System

Windows

### What happened

Clicking "Change spool" shows a broken header:

![afbeelding](https://github.com/fluidd-core/fluidd/assets/305679/ab0cb364-390f-46de-8442-4c9920610421)

### What did you expect to happen

Normal panel title

### How to reproduce

Use spoolman 0.16.1 and fluidd 1.28.0

**Comment by Cyondil** [comment]
Also seeing the same here.

![image](https://github.com/fluidd-core/fluidd/assets/89946331/e065e5ea-428a-40af-9e34-9cbd43179a1e)

**Comment by pedrolamas** [comment]
Hi @thijstriemstra and @Cyondil, thank you for reporting this issue.

My apologies for this, I missed it on a refactor I did, but this will be fixed on the next release v1.28.1
