### ISSUE TITLE
tools: add PROBE_ACCURACY 

### ISSUE THREAD

**Issue by thijstriemstra** [fluidd-core/fluidd#1364]
### Fluidd Version

1.28

### Browser

Firefox

### Device

Desktop PC

### Operating System

Windows

### What happened

The tools menu has `PROBE_CALIBRATE` but not `PROBE_ACCURACY`

![afbeelding](https://github.com/fluidd-core/fluidd/assets/305679/f0ccf97e-b95a-4c05-8e55-8df1aa637950)

### What did you expect to happen

I'd expect `PROBE_ACCURACY` to be in the list as well.

### How to reproduce

Enable Voron TAP probe.

**Comment by pedrolamas** [comment]
Hi @thijstriemstra, thank you for opening this ticket.

The lack of a feature is not in itself a but, so I am changing the ticket labels as such.

As the command is mainline Klipper, I do think we can add this for next release!
