### ISSUE TITLE
Runout Sensor

### ISSUE THREAD

**Issue by cupoe13** [fluidd-core/fluidd#1379]
### Is your feature request related to a problem? Please describe

No, there is not a problem.

### Describe the solution you'd like

Currently there is a section for a Runout Sensor on the Tune page.  Could that be an option for the user to add it to the Home page.  Either under the "Fan & Outputs" section or a new section that can be added or removed in the layout.

### Additional information

I have an Artillery Sidewinder X2 which has a runout sensor.  I noticed on Mainsail that the runout sensor is on the dashboard, but it wasn't on Fluidd.  I ended up finding it on the Tune page though, so figured it would be an easy request to get it added to the Home page.

**Comment by pedrolamas** [comment]
Hi @cupoe13 thank you for opening this feature request!

This sounds like a reasonable request and makes complete sense!

We will make an effort to try and add this for the next release!
