### ISSUE TITLE
Spoolman Materials column is empty

### ISSUE THREAD

**Issue by NovaViper** [fluidd-core/fluidd#1384]
### Fluidd Version

1.28.1

### Browser

Other (Please tell us below)

### Device

Desktop PC

### Operating System

Linux

### What happened

When I open the "Change Spool" dialog for Spoolman, it shows all of the spools but the Material column is completely blank. The browser I'm using is Vivaldi

### What did you expect to happen

The material column in the interface should be filled with the spool's material information

### How to reproduce

1. Enable Spoolman support
2. Add some spools
3. Open Fluidd's Change spool interface
4. Everything but the material information is filled out

### Additional information

![image](https://github.com/fluidd-core/fluidd/assets/7191115/775d2885-b6e4-4a90-baf3-f6f901fe4559)

**Comment by pedrolamas** [comment]
Hi @NovaViper, thank you for opening this ticket.

Can you please confirm what version of Spoolman you are using? If you open Spoolman, the version should be visible on the bottom of the page.
