### ISSUE TITLE
Missing some strings for translation

### ISSUE THREAD

**Issue by AndylgTom** [fluidd-core/fluidd#1394]
### Fluidd Version

v1.29.0

### What happened

The 1 screenshot show the text, it is missing in the yaml for translation into other languages. Please add them.
And 2 screenshot, you can remove the explanatory text (it is essentially unnecessary because it duplicates the main text).

![Снимок экрана 2024-03-17 204957](https://github.com/fluidd-core/fluidd/assets/20997012/f03715d1-1606-4775-8a0c-a3fef6d8a2cb)

![Снимок экрана 2024-03-17 205843](https://github.com/fluidd-core/fluidd/assets/20997012/18e8e546-a77c-430a-b4ec-8f4b2c619fec)

**Comment by pedrolamas** [comment]
Hi @AndylgTom, thank you for opening this ticket.

> ![Снимок экрана 2024-03-17 204957](https://private-user-images.githubusercontent.com/20997012/313483187-f03715d1-1606-4775-8a0c-a3fef6d8a2cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2ODkzOTgsIm5iZiI6MTcxMDY4OTA5OCwicGF0aCI6Ii8yMDk5NzAxMi8zMTM0ODMxODctZjAzNzE1ZDEtMTYwNi00Nzc1LThhMGMtYTNmZWY2ZDhhMmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE1MjQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNzE5ZmNhMjM2YzcwOTVhNmFkYWRhM2ViYjFkYTc5MWU4YjMzOGQxZDBjN2VmYjk2NzNmNWU4ZTgwNGY2Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wcauWaORDnmBMp1EgoU3lUTHH2pdQconKpnwNbgQHYA)

The above message is a Klipper error message (which I believe are all in English and non-localizable), so it is outside of the control of Fluidd - not much we can do here, I'm afraid...

> ![Снимок экрана 2024-03-17 205843](https://private-user-images.githubusercontent.com/20997012/313481562-18e8e546-a77c-430a-b4ec-8f4b2c619fec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2ODkzOTgsIm5iZiI6MTcxMDY4OTA5OCwicGF0aCI6Ii8yMDk5NzAxMi8zMTM0ODE1NjItMThlOGU1NDYtYTc3Yy00MzBhLWI0ZWMtOGY0YjJjNjE5ZmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE1MjQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNWNhYjlmOTk2ZmQ4ZjQ4YzIxZTg2NTM0NjljMDkzYzlkM2FlYzg3YmY3YmM0MTA1NTk2NzBiZDMyM2FiZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.spk7vXHdjhSzyKi_T2N-clJU7TxyKWvO74szLxEcgQU)

Regarding this one, indeed it does seem a bit "overkill" as the label already says all that needs to be said... we will take a look into this as to simplify it.
