### ISSUE TITLE
Fail after update

### ISSUE THREAD

**Issue by yuranikspb** [fluidd-core/fluidd#1412]
### Fluidd Version

v1.29.1

### Browser

Chrome

### Device

Desktop PC

### Operating System

Linux

### What happened

after update from v1.23.3 to v1.29.1 with ui update manager  have an error in UI 
Location at option 'path: /home/pi/fluidd' is within a git repo. Found .git folder at '/.git'
Also kiauh show version installed v1.29.1
update manager show versionv 1.23.3

![image](https://github.com/fluidd-core/fluidd/assets/1639829/8cb12687-e3e4-4b03-8c55-d58059821b41)

### What did you expect to happen

Printer work fine, but error in update manager UI.Also  recover button not helped.
I try to reinstall with kiauh ( remove and install)  but not helped.

### How to reproduce

update from v1.23.3 to v1.29.1

### Additional information Moonraker log

Owner: fluidd-core
Repository Name: fluidd-config
Path: /home/pi/fluidd-config
Remote: origin
Branch: master
Remote URL: https://github.com/fluidd-core/fluidd-config.git
Recovery URL: https://github.com/fluidd-core/fluidd-config.git
Current Commit SHA: ce48c5854e9ca3ca72b63d0327069fac20e94c7c
Upstream Commit SHA: ce48c5854e9ca3ca72b63d0327069fac20e94c7c
Current Version: v1.2.0-0-gce48c585
Upstream Version: v1.2.0-0-gce48c585
Rollback Commit: ce48c5854e9ca3ca72b63d0327069fac20e94c7c
Rollback Branch: master
Rollback Version: v1.2.0-0-gce48c585
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 0
Diverged: False
2024-04-12 10:35:56,532 [base_deploy.py:log_info()] - Git Repo fluidd-config: Channel: dev
2024-04-12 10:35:56,532 [base_deploy.py:log_info()] - Git Repo fluidd-config: Validity check for git repo passed
2024-04-12 10:35:56,540 [base_deploy.py:log_info()] - Web Client fluidd: Invalid Installation, aborting remote refresh
2024-04-12 10:35:56,541 [base_deploy.py:log_info()] - Web Client fluidd: Detected
Repo: fluidd-core/fluidd
Channel: stable
Path: /home/pi/fluidd
Local Version: v1.23.3
Remote Version: v1.29.1
Valid: False
Fallback Detected: False
Pre-release: False
Download Url: https://github.com/fluidd-core/fluidd/releases/download/v1.29.1/fluidd.zip
Download Size: 3684373
Content Type: application/zip
Rollback Version: v1.23.3
Rollback Repo: ?
Warnings:
 Location at option 'path: /home/pi/fluidd' is within a git repo. Found .git folder at '/.git'
 Failed to validate installation

**Comment by matmen** [comment]
Hi, thanks for opening this issue. This isn't a fluidd issue, but the reason you're only seeing the warning now is because we only started showing them recently.
The warning message indicates you have a git repository initialized in your root path (`/`), hence the `/.git` location. You probably accidentally ran `git initialize` or `git clone` in the wrong directory. I would advise you to remove the `/.git` directory, making sure there are no files in it you don't want to lose.
