### ISSUE TITLE
Camera-Streamer as option for crowsnest

### ISSUE THREAD

**Issue by fabiandj64** [fluidd-core/fluidd#1429]
### Is your feature request related to a problem? Please describe

Could you please add the camera-streamer functionality to work with fluidd?

### Describe the solution you'd like

Crowsnest camera-streamer mode to work with fluidd

**Comment by pedrolamas** [comment]
Hi @fabiandj64 , thank you for opening this ticket.

That was added almost 1 year ago in https://github.com/fluidd-core/fluidd/pull/1107

**Comment by fabiandj64** [comment]
My bad...
