### ISSUE TITLE
Please stop using a blocking modal for file download, it's a horrible design feature

### ISSUE THREAD

**Issue by h3rb** [fluidd-core/fluidd#1430]
### Is your feature request related to a problem? Please describe

Using a blocking modal is horrible design for this feature.  I should be able to navigate the UI and look through the print status without downloading the file being the blocker.  Sometimes I need to immediately glance at the print process, and this modal makes it impossible for me to scroll the window.  

### Describe the solution you'd like

**It shouldn't be a modal anyway, this is the age of multitasking -- you can just put it in place of the gcode preview while in progress, since I assume that is why the file must be downloaded.**

### Describe alternatives you've considered

Making the modal smaller and part of the accordion (at the top), in a folded way, so that you can see progress and open it to cancel or interact or get more detail.

**Comment by pedrolamas** [comment]
Hi @h3rb, thank you for opening this ticket.

Considering your other #1431 ticket, I am going to assume you are using Fluidd v1.19, which indeed we had blocking dialog downloads.

I suggest you update to the latest Fluidd v1.30.0 as we no longer use blocking downloads.
