### ISSUE TITLE
Cancelling Download doesn't really cancel the download request

### ISSUE THREAD

**Issue by h3rb** [fluidd-core/fluidd#1431]
### Fluidd Version

v1.19.0-6184c73

### Browser

Chrome

### Device

Desktop PC, Laptop, Mobile device (Phone, Tablet or similar)

### Operating System

Windows, Android

### What happened

When I load up a fluidd UI in  v1.19.0-6184c73 I see "Downloading file" .. for printers or on mobile with low bandwidth issues I want to cancel this immediately but it keeps refreshing and does not cancel or abort.  It repeatedly recreates the download modal and continues to hog screen and bandwidth .. as a modal it makes fluid unusable in this use case.

### What did you expect to happen

File would not be resumed, modal would go away. 

### How to reproduce

Put a printer on Wifi only and drive out to a low # of bars, use octoeverywhere or a VPN, and try to cancel the download when the fluidd interface is loaded.

**Comment by pedrolamas** [comment]
Hi @h3rb, thank you for opening this ticket, however Fluidd v1.19 is almost 2 years old now and that bug has long been fixed.

I suggest you update to the latest Fluidd v1.30.0.
