### ISSUE TITLE
Show remaining length from Spoolman

### ISSUE THREAD

**Issue by AndreKR** [fluidd-core/fluidd#1442]
### Is your feature request related to a problem? Please describe

When the Spoolman integration is enabled, the remaining weight on the spool is shown:

![image](https://github.com/fluidd-core/fluidd/assets/1188538/310d8fd4-2bec-49da-af86-1800170946e6)

But when I go to Jobs I only see the length of filament needed:

![image](https://github.com/fluidd-core/fluidd/assets/1188538/c74d02de-f1ba-45eb-a4f4-fe79dddfd2c0)

This makes sense because the slicer doesn't know the density of the filament, that is only stored in Spoolman.

### Describe the solution you'd like

Spoolman knows the density of the filament:

![image](https://github.com/fluidd-core/fluidd/assets/1188538/a74d01da-1a5d-4a6d-b398-87fa30dc17f5)

So if fluidd would calculate and show the remaining *length* instead/in addition to the remaining weight, it would make it easier to find spools with suitable amounts of filament remaining.

**Comment by AndreKR** [comment]
Actually fluidd probably doesn't even have to do the calculation. Spoolman shows the remaining length in its UI:

![image](https://github.com/fluidd-core/fluidd/assets/1188538/070bb6d9-0878-481a-914a-1557b0787b32)

So I would assume it's available through the API as well.

**Comment by matmen** [comment]
Hi, thanks for your request. Would a simple setting to switch between remaining weight and length suffice or would you prefer to see both values at the same time?

**Comment by AndreKR** [comment]
The ability to switch to length would be fine for me, I don't need to see both at the same time. Not sure if that is really simpler, implementation-wise. 🤷

**Comment by matmen** [comment]
Thanks. A setting to switch between weight and length units will be included with the next fluidd release :)
