### ISSUE TITLE
Temperature sensor name incorrect

### ISSUE THREAD

**Issue by thijstriemstra** [fluidd-core/fluidd#1460]
### Fluidd Version

1.30.1

### Browser

Firefox

### Device

Desktop PC

### Operating System

Windows

### What happened

I defined:

```
[temperature_sensor RPI_3B+]
sensor_type: temperature_host
min_temp: 0
max_temp: 100
```

And it shows up as `RPI 3 B`:

![afbeelding](https://github.com/fluidd-core/fluidd/assets/305679/ee471e2b-9ae4-4ea5-abe5-ac8b89c1a5fb)

### What did you expect to happen

That it shows up as `RPI 3B+` (like KlipperScreen does).

### How to reproduce

Define:

```
[temperature_sensor RPI_3B+]
sensor_type: temperature_host
min_temp: 0
max_temp: 100
```

**Comment by MPFGlaser** [comment]
Good catch. Facing the same issue, but didn’t find yours since I searched for “spaces” and made my own. Good to see they’re merged now, though!

**Comment by thijstriemstra** [comment]
Maybe you can copy paste your original report here as well, had a lot of extra info @MPFGlaser
