### ISSUE TITLE
Current Layer information and gcode preview not showing print information, when printing, unless I restart my browser or slicer (Orcaslicer)

### ISSUE THREAD

**Issue by pmbroth** [fluidd-core/fluidd#1461]
### Fluidd Version

Current version 

### Browser

Chrome, Firefox, Edge

### Device

Desktop PC, Laptop

### Operating System

Windows

### What happened

One observation, layers and gcode preview do not show after sending job to printer, if I exit the slicer and reload and then look at device, everything is displayed (Even when I just send the job to the printer, and it is first starting up, I refresh the browser and all information is there) . It is like the printer is not refreshing information to browser or slicer. The same thing occurs, if I have a browser open to the device,

I waited for the printer to initialize and print, I waited for about 6 layers, and no updated information, unless I refresh my browser or reload slicer.

One new observation, If printing job from job list, layers and Goode preview are ok from start.

### What did you expect to happen

Layers and Gcode preview to show starting information and continue with progress. 

### How to reproduce

See my "What Happened"

### Additional information

Latest Debian, Latest Klipper, and most current Fluid.  Using this image for my Qidi X-max 3

https://github.com/CChen616/QIDI_Max3_Bookworm

**Comment by pedrolamas** [comment]
HI @pmbroth , thank you for opening this ticket.

We will however require that you indicate the specific version of Fluidd you are using (shown on the bottom right of Fluidd).

I also ask that you upload a sample gcode file so that we can use that to try and reproduce this issue.

**Comment by pmbroth** [comment]
her you go  
![image](https://github.com/user-attachments/assets/8f62c403-cd57-4b25-8855-7689b26b3568)

**Comment by pmbroth** [comment]
If i print from a slicer - qidislicer, orcaslicer, it happens with both.  I close the browser or the application, and reconnect, and the layer information is there.

**Comment by pmbroth** [comment]
I will get a gcode file shortly.

**Comment by pmbroth** [comment]
[boxtestgcode.zip](https://github.com/user-attachments/files/16459641/boxtestgcode.zip)


gcode from orcaslicer


![image](https://github.com/user-attachments/assets/5d912807-9c12-481d-a330-21110e5807b6)

**Comment by pedrolamas** [comment]
You are currently missing the `SET_PRINT_STATS_INFO` entries on your gcode, and that will cause incorrect layer counts displayed in Fluidd (and the same issue on other frontends too).

Please check [here](https://github.com/fluidd-core/fluidd/issues/1403#issuecomment-2028681847) on how to add that to your Orca settings.

Once you add that, reslice the file and it will include `SET_PRINT_STATS_INFO` entries that will fix the layer count issue.
