### ISSUE TITLE
Web interface not visible

### ISSUE THREAD

**Issue by T9Air** [fluidd-core/fluidd#1473]
### Fluidd Version

v1.30.1

### Browser

Chrome

### Device

Laptop

### Operating System

Windows

### What happened

If I try to go to fluidd in my browser, it looks like it is fully loaded, with the logo at the top of the tab, etc. but the browser page is blank, with no UI visible. I even tried reinstalling Fluidd, and it did not help

### What did you expect to happen

I expect to be able to see and be able to interact with the Fluidd web interface

### How to reproduce

I think I changed the trusted_clients option in the moonraker.conf to my laptops IP address, but it did work after that. I also installed Sonar. Then it randomly stopped working. When I tried to reinstall it, it still did not work. Even removing Sonar did not help.

**Comment by franco443** [comment]
try to clear your browser cache. That did the trick for me on browser. I am still trying to figure orcaslicer out its doing that to me there for fluidd interface. That should work for you though on browser. I have chrome too. Hope that works for you.

**Comment by T9Air** [comment]
I tried that, didn't work.

**Comment by T9Air** [comment]
@pedrolamas I reset all of my changes, and it was still showing nothing.

**Comment by pedrolamas** [comment]
In that case, you might want to press F12 to open the in-browser dev tools and check the console there for errors

**Comment by T9Air** [comment]
I get this error: `index-DmW-YI4h.js:254 WebSocket connection to 'ws://3dprintermanager:7125/websocket' failed: WebSocket is closed before the connection is established.` Do you know how I could fix it?

**Comment by T9Air** [comment]
Mainsail does work if that would change anything.

**Comment by pedrolamas** [comment]
Please upload your moonraker.log here, that might help to understand what is going on.

**Comment by T9Air** [comment]
[moonraker.log](https://github.com/user-attachments/files/16588970/moonraker.log)

**Comment by grilparto** [comment]
Wanted to add another datapoint.  I'm having the same issue.  It occurred after trying to adjust my layout.  I experienced some odd behavior upon exiting the layout adjustment mode.  Each column on the UI was showing a mix of the actual UI element and also the layout adjustment behavior.  After refreshing the page, blank (white) page as described above.  Also seeing the same "failed: WebSocket is closed before the connection is established." in my Chrome console (given that we're both having the same blank page issue and websocket failure, it seemed like both our issues could be related).

Tried clearing website data, tried a different browser, tried a browser on a different PC also.  Removed and reinstalled fluidd, then removed fluidd, removed moonraker, and then reinstalled both of those as well.  Also tried removing/reinstalling fluidd and moonraker again, but also deleting the moonraker.conf to make sure a new one would be created after the reinstall.  

Also attaching my moonraker.log

[moonraker.log](https://github.com/user-attachments/files/16619076/moonraker.log)

**Comment by pedrolamas** [comment]
Can I ask that you access http://moonraker-ip-or-host:7125/server/database/item?namespace=fluidd (replacing `moonraker-ip-or-host` with the correct IP or hostname for the moonraker instance) and paste the results here?

We've previously had reports of similar issues with the dashboard causing the page to go blank, and this might help to get to the bottom of this issue.

**Comment by T9Air** [comment]
[fluidd.txt](https://github.com/user-attachments/files/16625587/fluidd.txt)

**Comment by pedrolamas** [comment]
Thank you @T9Air, I can see the problem clearly on that and I will provide a fix for next release!
