### ISSUE TITLE
Traditional Gcode uses = for parameters

### ISSUE THREAD

**Issue by pellcorp** [fluidd-core/fluidd#1481]
### Fluidd Version

 v1.30.2

### Browser

Firefox

### Device

Desktop PC

### Operating System

Linux

### What happened

For the K1, the M106 command is redefined to fix the mappings for slicers, but if you try and use this command fluidd passes the S and P parameters with =, but this is a traditional gcode command, it should be passed without =.

It passed the M106 command like so:
M106 P=0 S=250

### What did you expect to happen

I expected the M106 command to pass a command like so:
M106 P0 S250

### How to reproduce

Define a traditional gcode macro and execute it passing parameters

**Comment by pedrolamas** [comment]
Hi @pellcorp, thank you for opening this ticket.

Klipper should still work fine when calling the parameters with `=`, are you actually getting any error when Fluidd sends `M106 P=0 S=250`?
