### ISSUE TITLE
G-Code Preview Show Very Drastically incorrect number of layers - File Exported from Cura Ultimaker 5.8

### ISSUE THREAD

**Issue by soundtechscott** [fluidd-core/fluidd#1490]
### Fluidd Version

v0.12.0-102-g9f41f53c

### Browser

Chrome

### Device

Desktop PC

### Operating System

Windows

### What happened

I builld a file in Cura Ultimaker 5.8
slice, export to G-code or Upload directly to 3d printer
Fluidd shows correct number of layers in Printing window

but DRASTICALLY incorrect number of layers in the G-Code Preview window

![image](https://github.com/user-attachments/assets/20d0ac11-4774-4645-9432-285e080105cc)

[EN4PRO_ Front Link.zip](https://github.com/user-attachments/files/16808366/EN4PRO_.Front.Link.zip)
[EN4PRO_Front Link.zip](https://github.com/user-attachments/files/16808367/EN4PRO_Front.Link.zip)

### What did you expect to happen

I expect it to match....

### How to reproduce

slice, upload, look 

### Additional information

this worked just fine in a previous version of fluidd
and I dont know why it doesnt work now

**Comment by pedrolamas** [comment]
Hi @soundtechscott, thank you for opening this ticket.

This is actually expected behavior as Cura does not directly provide layer information to Klipper; my recommendation is that you use my [Klipper Preprocessor script for Cura](https://github.com/pedrolamas/klipper-preprocessor) to ensure that all sliced files have the necessary data.

**Comment by soundtechscott** [comment]
this worked fine in cura 5.7
what has changed with fluidd/klipper that has now made cura not work

**Comment by pedrolamas** [comment]
> what has changed with fluidd/klipper that has now made cura not work

Nothing changed in Fluidd or Klipper side, it might have changed in Cura 5.8, but that I cannot say... nevertheless, both Fluidd and Mainsail have always recommended using that script in Cura to ensure that the output g-code is fully compatible with the Klipper ecosystem.

**Comment by pedrolamas** [comment]
@soundtechscott I just realized that on the initial post you indicated you are using Fluidd v0.12.0, which is more than 3 years old!

The odd bit is that I can't find the full version "v0.12.0-102-g9f41f53c", so maybe you are actually using a fork (altered copy) of Fluidd?

**Comment by soundtechscott** [comment]
installed straight from Kiauh
I'm only just now 1 version off according to this

![image](https://github.com/user-attachments/assets/02a21bf5-50d9-46a9-b306-a9cd50b58d53)

**Comment by soundtechscott** [comment]
and inside Fluidd
![image](https://github.com/user-attachments/assets/c790d5d8-f3bf-461a-89c6-18c78a998e0e)

**Comment by soundtechscott** [comment]
also
I am up to date according to these links

https://www.klipper3d.org/Releases.html
https://github.com/fluidd-core/fluidd/releases


I switched to the octopus pro board on my neptune to get away from a "Fork" and have the standard klipper
because elegoo does stupid things in their hacked up firmware

**Comment by pedrolamas** [comment]
> and inside Fluidd
> ![image](https://private-user-images.githubusercontent.com/51548286/363241114-c790d5d8-f3bf-461a-89c6-18c78a998e0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMzM2NzEsIm5iZiI6MTcyNTAzMzM3MSwicGF0aCI6Ii81MTU0ODI4Ni8zNjMyNDExMTQtYzc5MGQ1ZDgtZjNiZi00NjFhLTg5YzYtMThjNzhhOTk4ZTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDE1NTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYTFkOGUwNjYwZmY3ZTJhMzY2ODJkNzUzNTYyYzNjZmYxNjQ2ZTU1OGQ4Y2NiMTcwYjJmMzBhMDU2NDIyOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lVTXuyklEsTK6eiR9hvMQMtqxXLTPgfEOBEiuVG2SNM)

Ah, you indicated the Klipper version, not Fluidd which is what was asked!

All explained then, and yes, you are using the most recent version of Fluidd! 🙂

**Comment by soundtechscott** [comment]
also, Cura claiming its your problem.....
so.. ????

![image](https://github.com/user-attachments/assets/2c943180-bf74-490c-aaac-95ec9f40b64f)

**Comment by pedrolamas** [comment]
They are correct about one thing: Cura does not produce the best g-code for Klipper, hence why I created that script and it has been promoted a helper tool.

Bottom line is that you should use the script above if you plan to slice files in Cura and then print them in a Klipper powered printer.
