### ISSUE TITLE
go2rtc api uri broken 

### ISSUE THREAD

**Issue by aam335** [fluidd-core/fluidd#1491]
### Fluidd Version

v1.30.3

### Browser

Chrome

### Device

Desktop PC, Laptop

### Operating System

Linux

### What happened

ws url for go2rtc webrtc broken:
ws://rockpi.local:1984/api/api/ws?src=cam

### What did you expect to happen

ws://rockpi.local:1984/api/ws?src=cam

### How to reproduce

select go2rtc camera source 

### Additional information

possibly you need to add origin any to go2rtc config
```
api:
  origin: "*"
```

**Comment by pedrolamas** [comment]
Hi @aam335, thank you for opening this ticket.

Can you confirm that you did indeed add this section to your go2rtc configuration?

```
api:
  origin: "*"
```

I ask this as you DO need to whitelist the domain, without that the browser will block the access with a CORS error!

**Comment by aam335** [comment]
> I ask this as you DO need to whitelist the domain, without that the browser will block the access with a CORS error!
@pedrolamas  it is not a CORS problem, go2rtc limits access to signalling ws to known referers.
https://github.com/AlexxIT/go2rtc/issues/118

**Comment by pedrolamas** [comment]
Sorry, but I just tested and can confirm that it does work if you do add the "api/origin" configuration.

![image](https://github.com/user-attachments/assets/7ea8fa50-97ad-49d1-9942-ae52874ec216)

If I remove the final 2 lines, the stream does not load, but once I add it, it works fine!

**Comment by pedrolamas** [comment]
What URL are you using? I just copied this one and used it in Fluidd!

![image](https://github.com/user-attachments/assets/fedc8024-9a4e-426b-83f7-816879187e10)

**Comment by aam335** [comment]
http://rockpi.local:1984/stream.html?src=cam&mode=webrtc
http://rockpi.local:1984/stream.html?src=cam

**Comment by pedrolamas** [comment]
I used the 2nd URL you have there and added a test camera on my system:

![image](https://github.com/user-attachments/assets/a35f73e0-c586-4ff4-9116-ead0c5303990)

That seems to load the correct URL: 

![image](https://github.com/user-attachments/assets/ecaf3133-cb90-4bff-8c38-0fc720ed09dc)

**Comment by aam335** [comment]
I confused snapshot and stream url )

http://rockpi.local:1984/api/frame.jpeg?src=cam

adds extra api

thanks!!!
