### ISSUE TITLE
Console output messed up

### ISSUE THREAD

**Issue by Rigattoni** [fluidd-core/fluidd#1501]
### Fluidd Version

v1.31.0-37 

### Browser

Firefox

### Device

Laptop

### Operating System

Windows

### What happened

I found a display issue when printing help command in the console. It is shown fine in the console tab.
Further more: The delete button in the small console does not work correctly. At least if you have the screen as shown in the pic
<img width="513" alt="image" src="https://github.com/user-attachments/assets/85002dba-c8f2-46b1-9427-ac3e016e3753">

### What did you expect to happen

No overlapping of different text parts.
Delete button to be working.

### How to reproduce

Type help in the console on the main screen.

**Comment by HelgeKeck** [comment]
this is the wrong github repo, please repost it here
https://github.com/fluidd-core/fluidd

**Comment by HelgeKeck** [comment]
i had this as well once or twice, it happens always when we output some html code, not sure if this is related to the mainline, thats why i suggest to repost it and close this one here

**Comment by pedrolamas** [comment]
Closing now as this is not a mainline Fluidd issue.
