### ISSUE TITLE
jobs: hide .mru files

### ISSUE THREAD

**Issue by thijstriemstra** [fluidd-core/fluidd#1503]
### Fluidd Version

1.30.4

### Browser

Firefox

### Device

Desktop PC

### Operating System

Windows

### What happened

The jobs page has `.mru` files in it:

![afbeelding](https://github.com/user-attachments/assets/6e3a03ac-fc6c-4c4a-b079-ef5cd825be0d)

I enabled the hidden files filter.

### What did you expect to happen

That .mru files are hidden.

### How to reproduce

Not sure..!

**Comment by thijstriemstra** [comment]
my guess is mru stands for moonraker upload? i'll try to search moonraker codebase.

**Comment by thijstriemstra** [comment]
my guess is they're unprocessed or failed moonraker uploads? not sure how they ended up in this state though.

**Comment by thijstriemstra** [comment]
.> my guess is they're unprocessed or failed moonraker uploads? not sure how they ended up in this state though.

cc @arksine

**Comment by Arksine** [comment]
Moonraker streams uploads to the system temp folder with a temporary file name (with the .mru extension).  Once the upload is complete, the file is moved to the destination path and renamed.  The only way I'm aware that a `.mru` file could be moved  without being renamed is if the upload request either omitted the multipart filename or passed an empty value.  Its very unlikely that Fluidd did this unless its a browser bug, however it may be possible that some other software did.

I added a check to the upload method to make sure it receives a valid file name.  That said, if this behavior continues `moonraker.log` might be useful in tracking down what would cause this.

**Comment by thijstriemstra** [comment]
thanks for the feedback @Arksine!

**Comment by thijstriemstra** [comment]
> That said, if this behavior continues moonraker.log might be useful in tracking down what would cause this.

@Arksine I got the new 400 error you added recently while uploading a file from OrcaSlicer. It showed up in a OrcaSlicer popup:

```
Error uploading to print host:
dd0b:319:6e26::130: curl:Couldn't connect to server:
Failed to connect to dd0b:319:6e26::130 port 80: Connection refused
[Error 7]
192.168.2.181: HTTP 400: {"error":{"code":400,"message":"Bad Request","traceback":"Traceback
(most recent call last):\n\n File
\"/home/foo/moonraker-env/lib/python3.11/site-packages/tornado/web.py\", line 1790, in
_execute\n result = await result\n ^^^^^^^^^^^^\n\n File
\"/home/foo/moonraker/moonraker/components/application.py\", line 1001, in post\n raise
tornado.web.HTTPError(400, \"Multipart filename omitted\")\n\ntornado.web.HTTPError: HTTP
400: Bad Request (Multipart filename omitted)\n"}}
```

I uploaded a file with title: `Z-Stepper Spacer_ASA_23m6s.gcode` It would fail everytime I uploaded.

After changing the name to `Z-Stepper_Spacer_ASA_23m6s.gcode`, thus eliminating the space in filename, it worked properly.

So where is the issue, Moonraker or OrcaSlicer?

**Comment by Arksine** [comment]
Sounds like an issue in Orcaslicer.  Its uploading a file without properly setting the filename in the `Content-Disposition` header.

FWIW, I uploaded a file with PrusaSlicer 2.8.1 using the same file name and it proceeded successfully.
