### ISSUE TITLE
Fluidd not handing reverse proxy real IP

### ISSUE THREAD

**Issue by whc2001** [fluidd-core/fluidd#1515]
### Fluidd Version

v1.30.5

### Browser

Edge

### Device

Desktop PC

### Operating System

Windows

### What happened

I wanted to access my printer from the Internet through my reverse proxy while ultilizing the built-in account function. I setup everything however the WebUI is always accessable even through the Internet and account is always showing "Trusted user". By observing `printer_data/logs/fluidd-access.log`, all the requests are showing up as coming from my reverse proxy host, even if my reverse proxy has `X-Forwarded-For` and `X-Real-IP` set up.

### What did you expect to happen

Fluidd should show the login page when the source of the request coming from reverse proxy is not in `trusted_clients`

### How to reproduce

1. Setup Klipper and Fluidd
2. Add an account
3. Setup reverse proxy (Nginx with proxy_set_header, or Caddy default headers)
4. Access from public network, Fluidd shows main page directly

### Additional information

Actually I am not sure if this is a Fluidd problem or a Moonraker problem, but it mostly seem to be related to Fluidd

**Comment by matmen** [comment]
Thanks for your report. Authentication is handled by [moonraker](https://github.com/Arksine/moonraker) directly, so I would suggest opening an issue / feature request there. IMO, in this case, authentication should be handled by the reverse proxxy though ;)
