### ISSUE TITLE
Column Order

### ISSUE THREAD

**Issue by llambion72** [fluidd-core/fluidd#1538]
### Is your feature request related to a problem? Please describe

Is it possible to add the possibility of placing columns in a custom order? 

### Describe the solution you'd like

In the task panel I would like to change the order of some columns. Could it be possible to add the possibility of clicking on the header of a column and moving it to the left or right as needed?

**Comment by pedrolamas** [comment]
Hi @llambion72 thank you for opening this Feature Request.

I've started working on this, I can tell you right now that probably I won't be able to make it work directly by dragging columns, but it will work fine from the column picker (which is what I have already implemented and am testing as part of #1539)
