### ISSUE TITLE
Navigate when adjusting dashboard layout

### ISSUE THREAD

**Issue by thijstriemstra** [fluidd-core/fluidd#1545]
### Fluidd Version

1.31.1

### Browser

Firefox

### Device

Desktop PC

### Operating System

Windows

### What happened

When you "adjust dashboard layout" on a page other than the dashboard, it'll show 2 buttons but there's nothing to adjust:

![afbeelding](https://github.com/user-attachments/assets/12406e27-61ab-4036-8594-63499645a517)

### What did you expect to happen

To navigate to the dashboard when clicking "adjust dashboard layout"

**Comment by pedrolamas** [comment]
Hi @thijstriemstra thanks for opening this issue.

Currently there are 2 places where one can edit the layout: the Dashboard and the Diagnostics (when enabled)

I guess we can disable that button on the other pages, so we'll make sure that happens for the next release.

**Comment by thijstriemstra** [comment]
I guess that works, but ideally the whole layout edit thing is moved out of the menu and placed somewhere on each section where it's relevant. It took me a while before I discovered the layout edit feature, it's sort of hidden in the menu right now.
