### ISSUE TITLE
Camera setup not working 

### ISSUE THREAD

**Issue by Akshar062** [fluidd-core/fluidd#1553]
### Fluidd Version

v1.31.2

### Browser

Chrome

### Device

Desktop PC, Laptop, Mobile device (Phone, Tablet or similar)

### Operating System

Windows

### What happened

When i added camera and set camera i got invalid camera rotation snackbar and then camera preview came  but after refresh camera was gone

### What did you expect to happen

It should save camera state

### How to reproduce

just open chrome type ip and go to setting and set camera just give it name and then save it will show error then go to home there will be camera preview and refresh page camera is gone from dashboard and home also

### Additional information

I am using Elegoo neptune 4 plus

**Comment by Akshar062** [comment]
klipper
? -> v0.9.1-612

moonraker
? -> v0.7.1-0

octoeverywhere
3.6.3-6-g98dc8a

if it help

**Comment by pedrolamas** [comment]
Hi @Akshar062 thank you for opening this ticket.

Please that you take a screenshot of your camera settings and paste it here.

**Comment by Akshar062** [comment]
![image](https://github.com/user-attachments/assets/08399d5a-a70a-4481-b9f1-da0e25bdb0cf)
![image](https://github.com/user-attachments/assets/42aeb0da-de8b-49ce-b7a5-655ec5aa9bb0)

**Comment by Akshar062** [comment]
![image](https://github.com/user-attachments/assets/34c4236d-d3c0-4bd7-b52f-ffeac35237c3)

this comes after refresh it is gone


![image](https://github.com/user-attachments/assets/5a55150f-9a9f-4607-9b80-82b7d9a65498)

**Comment by pedrolamas** [comment]
Current Fluidd (which you are using) requires at least Moonraker v0.8.0-309

Your Moonraker version is far too old, either you update that to a more recent version or you will need to use whatever Fluidd version Elegoo provided.
