### ISSUE TITLE
Device copy button not working

### ISSUE THREAD

**Issue by thijstriemstra** [fluidd-core/fluidd#1556]
### Fluidd Version

1.31.3

### Browser

Firefox, Safari

### Device

Desktop PC, Mobile device (Phone, Tablet or similar)

### Operating System

Windows, iOS

### What happened

The copy buttons are not working, nothing is copied to the clipboard.

![afbeelding](https://github.com/user-attachments/assets/d52fb4eb-538b-4e67-9fdf-6ce477e79ff7)

### What did you expect to happen

Content in clipboard after copy.

### How to reproduce

Copy any field and try to paste somewhere.

**Comment by pedrolamas** [comment]
Hi @thijstriemstra I just tested this in Windows with Edge Dev and Firefox and it worked on both... I will perform more tests, but might be something else at play here.

Are you accessing Fluidd via http or https ?

**Comment by pedrolamas** [comment]
Ok, I just tested with http only access and seems `navigator.clipboard` is not available on that context (seems it required "secure" https context).

There seems to be some workarounds, so I will look into implementing those instead.
