### ISSUE TITLE
Add ability to slot a macro button in to mesh leveling panel in UI

### ISSUE THREAD

**Issue by tobyak** [fluidd-core/fluidd#177]
Well... just that.

A single macro button added to mesh leveling UI to allow users to use their own homing macros for non standard machines without the need to go to terminal or mian page macro box

**Comment by cadriel** [comment]
I'll consider this as a part of the overall macro updates when they happen.

**Comment by matmen** [comment]
Closing this because of staleness, feel free to re-open if this is still an ongoing issue.
