### ISSUE TITLE
GCODE preview

### ISSUE THREAD

**Issue by Mechazawa** [fluidd-core/fluidd#181]
A gcode preview like octoprint has would be very usefull, especially if it can sync up to the current print

**Comment by blerrgh** [comment]
Seconded!

**Comment by Mechazawa** [comment]
https://user-images.githubusercontent.com/1144171/115144667-2b57ce00-a04e-11eb-87f3-c18614fe2e9b.mp4

**Comment by Mechazawa** [comment]
Just needs a bunch refactoring and UI changes and then I guess it's done

https://user-images.githubusercontent.com/1144171/115169943-b0c79680-a0bf-11eb-8644-67eeda572a61.mov

**Comment by johngianni** [comment]
Very Nice !

**Comment by Kragrathea** [comment]
Hi all. I am the author of the PrettyGCode plugin for OctoPrint. https://github.com/Kragrathea/OctoPrint-PrettyGCode

I recently decided to move to Fluidd and I would like to get my plugin working with it. Possibly in the UI or more likely as a stand alone web app that uses the API. 

To figure that out I would like to try out this GCode preview. But I can't figure out how to enable it.  I am not yet familiar with Vue development. I assume it would have to be done by rebuilding Fluidd?

**Comment by StuSerious** [comment]
hey there @Kragrathea!
it's an honor to have you!
Currently @Mechazawa is very busy and his PR needs some of the final work. that's why it's currently disabled.

If you and a more effective back-and-forth communication, please join our discord here: https://discord.gg/GZ3D5tqfcF
We have internal testing branches that you could use and a lot of the devs are there to give you a hand!

Feel free to message me @ StuSerious#0404 so I can set you up with the proper roles :)
I wish you a great day!
~S

**Comment by cadriel** [comment]
Hi @Kragrathea 

This sounds great. I'd really like to make the gcode viewer a first class citizen when it comes to Fluidd. As mentioned, we already have some progress on this - however, if you're willing to put in the effort to maintain and implement something I'd be more than willing to help with this integration in Fluidd.

As Stu mentioned, join us on Discord and we can discuss further! :)

**Comment by Kragrathea** [comment]
Thanks for the quick replies! I did a bit more research and I think the first thing I need to do is get my code talking directly to Moonraker. After that I can figure out how to plug it into the Fluidd UI. So, I am not going to try to rebuild Fluidd with this GCode viewer right now.

**Comment by maruhe** [comment]
i updated to current release today
gcode-viewer is nice, but here the 'follow progress' seems not to work propper
also 'show current layer' would be a great feature and auto zoom to object sice
'follow progress' disables it self a bit oftain
and about layout - i'd prefer the bar's to change layer and progress below the preview - currently they need a lot of space
![grafik](https://user-images.githubusercontent.com/49123648/123009498-18020f80-d3bd-11eb-8af7-f46cfb82fe25.png)
looking forward to 3-column-dashboard :-*

**Comment by arjanmels** [comment]
Very nice!

Only the follow progress is not in sync with actual printing: the total number of layers is different between the preview and klipper status and there is an offset of a couple of layers between the current layer. Also the within layer progress (which is the most difficult I guess, is off).

**Comment by pedrolamas** [comment]
Thanks @harellevy, we might consider that for 1.19! 😉
