### ISSUE TITLE
3 Column Layout with Resizable Cards

### ISSUE THREAD

**Issue by 11chrisadams11** [fluidd-core/fluidd#189]
I think it would be nice to have an option to have a 3 column layout on the dashboard. Also, the ability to resize individual cards would be helpful. I would prefer to not have to scroll to see everything while printing, and currently some cards are just too large for my liking.

Thanks for the consideration

**Comment by phorsfi** [comment]
I have a very WIDE display on my printer which runs Fluidd in a browser via the Pi and would love to have drag/drop cards as well as a selection for multiple columns... The display is 1920x515px, 12" wide by about 5" tall and it would be great to use fluidd more easilly!

**Comment by maruhe** [comment]
3 Column Layout would be great - while center-column should be wider like OctoPrint with UI-Customizer

![grafik](https://user-images.githubusercontent.com/49123648/122658292-a5e6bc00-d16b-11eb-9fff-dbff4b1cffc5.png)

**Comment by grantemsley** [comment]
I'd really love to see this as well. I'm using a 4k monitor and there's tons of space on the sides that I wish I could make use of.

**Comment by XOIIO** [comment]
I'd also really like to have this, it seems like it should be simple. I have an 34" ultrawide monitor and fluidd really doesn't make great use of it. Seems like it should be pretty simple to add in for the layout editor too.
