### ISSUE TITLE
Full Screen webcam feed

### ISSUE THREAD

**Issue by PigeonFX** [fluidd-core/fluidd#279]
## Is your feature request related to a problem? Please describe.
(A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])

## Describe the solution you'd like:
Double-clicking on the webcam to go full screen rather than a 640x480 with maybe an emergency stop button.  
## Describe alternatives you've considered:
(A clear and concise description of any alternative solutions or features you've considered. Again, if possible, think about why these alternatives are not working out.)

## Affected users and/or setups:
I monitor my printing on phone and tablet, so would find having a full size screen of the stream very handy and a quick way to trigger emergency stop.
## Additional Context:
(Add any other context or screenshots about the feature request here.)

The current system of being able to bring up the stream smaller than the one already on the screen seems a little redundant.

![Capture](https://user-images.githubusercontent.com/39096995/117564189-c9194880-b0a2-11eb-9c1b-db2c799ac003.PNG)

**Comment by StuSerious** [comment]
hey there @PigeonFX!

this idea has been discussed and already has backend attention!
expect it in future releases!

cheers,
~S

**Comment by maruhe** [comment]
this is the point where I currently (have to) use OctoPrint
(with the 'Fullscreen Plugin') a double-click on the camera-image switches to this view where I have
*) camear in full-window-sice
*) information from printing-widget
*) pause-button (may with extra confirm)
*) full-screen-button to switch between full-window and full-screen

![grafik](https://user-images.githubusercontent.com/49123648/124357226-ad519f00-dc1a-11eb-8c12-2a6ffe6d44e2.png)

**Comment by pedrolamas** [comment]
On the next release we will provide a button to open the video feed in a new (separate) browser window/tab.

That will only have the feed, no buttons to control the print itself, so for that reason we will keep this ticket open to revisit going forward.
