### ISSUE TITLE
Timelapse playback / assign recorded Timelapse to jobs done

### ISSUE THREAD

**Issue by phil2sat** [fluidd-core/fluidd#303]
since there is the possibility to take timelapses via moonraker: https://github.com/FrYakaTKoP/moonraker/blob/dev-timelapse/moonraker/components/timelapse.py

https://github.com/FrYakaTKoP/moonraker/blob/dev-timelapse/docs/configuration.md

check if files exist in
output_path: ~/timelapse/ and play

a seamlesw integration would be nice, ive read about mainsail is planning to integrate this

thanks in advance,

**Comment by sdc53** [comment]
This seems like a relatively simple request.  Even adding this folder to the file browser tabs so we can download and delete them would be nice, currently doing this via winscp.
Would add it myself but not quite sure how..
