### ISSUE TITLE
Add button to the screen for built in klipper macros

### ISSUE THREAD

**Issue by DanielJoyce** [fluidd-core/fluidd#313]
I've searched and not seen the option, but it would be nice if we could add buttons to the screen that emit single g code commands, such as for manual bed leveling. Right now, we need to use the terminal, or define a 'custom macro' which all it does is wrap a built in macro/gcode.

**Comment by DanielJoyce** [comment]
Specifically, I'd like to have this for manual bed adjust, which doesn't seem to be a feature in fluidd yet?

**Comment by StuSerious** [comment]
hey there @DanielJoyce!

I recently discussed something similar with Cadriel, and it's going to be in the pipeline.
no ETA yet, but it will eventually make its way into fluidd!

as a quick reminder, PRs are always welcome <3

cheers,
~S

**Comment by fuzzynm** [comment]
If your looking just for manual bed leveling, define  [bed_screws], and the button BED_SCREW_ADJUST shows up on the tool window.

**Comment by lar3ry** [comment]
Not quite sure what you mean. Right now, if you put a macro into your printer.cfg, it will show up in the Macros box.
For example, I have three macros for manual be levelling, called Lev_LF, Lev_RF, and Lev_BK (I like to keep the names as short as possible). I also made another macro "folder" so I don't have to use or see the macros supplied with Fluidd.

You should have no reluctance about making macros in printer.cfg, even if they consist of just one GCode. You can make them visible as buttons or not.
Here's what I have for Lev_RF:

[gcode_macro Lev_RF]
gcode:
 G28
 G1 Z5
 G1 X290 F10000
 G28 Z

**Comment by StuSerious** [comment]
We since went back and worked a bit with the macros, I would consider this issue resolved.

@DanielJoyce do you agree?

**Comment by lar3ry** [comment]
On Sun, 2022-01-30 at 11:59 -0800, Stefano Serioli wrote:
> We since went back and worked a bit with the macros, I would consider
> this issue resolved.
> 
> @DanielJoyce do you agree?

Yes.
