### ISSUE TITLE
[v1.15.0] Movable Neopixel Color Picker.

### ISSUE THREAD

**Issue by Mitsuma** [fluidd-core/fluidd#332]
## Is your feature request related to a problem? Please describe.
When trying out the new Neopixel Color Picker I noticed that the window that opens is not movable.
This makes it a bit hard to see the changes if your layout has the camera/console above the color picker.

## Describe the solution you'd like:
Simply make the color picker movable, freely movable would be the best, like click and drag it around. 

## Affected users and/or setups:
Would help people who have their fan controls and camera a bit separate. Just a small change.

**Comment by Ramalama2** [comment]
@cadriel is it possible to add an color picker for rgb leds? Where you control each pin (red/green/blue) with pwm from 0.00 till 1.00 🙈
This would be amazing. Lets say if the names in the config files, matches something you like 🙈

If not, thanks anyway cadriel, thanks for fluidd it's amazing already as it is ♥️

**Comment by matmen** [comment]
@Nailig Sorry, but I can't reproduce this. Can you clear your browser cache and see if it still happens? For reference, this is the behavior on my end:
![chrome_HOIXhTJlb8](https://user-images.githubusercontent.com/25269274/158257466-05fd8fde-cb86-43c1-b0b4-d5ac6d0c3931.gif)
