### ISSUE TITLE
BME280 

### ISSUE THREAD

**Issue by Afterschnitzel** [fluidd-core/fluidd#335]
Hi. 
Is possible to show data from BME280 some where in temperature window (temperature, humidity, barometric pressure) without using macro in terminal?

Thanks in advance.

**Comment by cadriel** [comment]
I'll take a look - its hard to implement this without having one tho.

**Comment by Afterschnitzel** [comment]
Thank you. It is not expensive to afford one :-)

**Comment by pedrolamas** [comment]
Related to #434, I assume we can retrieve at least the humidity using the same approach

**Comment by samwiseg0** [comment]
> Related to #434, I assume we can retrieve at least the humidity using the same approach

From my understanding, The pressure will be present in the object using the BME280. In my example I do not have it as a value as my sensor does not support barometric pressure.

**Comment by pedrolamas** [comment]
@samwiseg0 indeed, seems to be the case!

I've got a few BME280's somewhere, I just need to find them and will start some tests...
