### ISSUE TITLE
[FR] Option to set time to 24h format

### ISSUE THREAD

**Issue by darkblaze69** [fluidd-core/fluidd#360]
After updating fluidd to 1.16.2 I get US 12h time format in predicitons and probably other places.
Just wanted an option to be able to see 24h format instead.

**Comment by StuSerious** [comment]
@darkblaze69 hey there!

thanks for the feature request, this was also brought up in the discord lately.
I think I can safely say you can expect a toggle button in the settings very soon!

cheers!
_~S_
