### ISSUE TITLE
 v1.16.2 cosmetic bug: firmware retraction values less than 0.25mm display as 0mm on GUI.

### ISSUE THREAD

**Issue by gregmatic** [fluidd-core/fluidd#366]
probably an old bug. front GUI will not display firmware retract retraction length properly if value is less than 0.25.

## Affected Version(s):
(The versions of fluidd this issue occurs on.)
- klipper version: v0.9.1-621-gdafb74e3 
- moonraker version: v0.7.1-25-g7f740cc -> v0.7.1-29 
- fluidd version:  v1.16.2

## Platform:
firefox

## Hardware Configuration:
N/A

## Reproduction Steps:
enable firmware retraction in printer.cfg with this:

[firmware_retraction]
retract_length: 0.249
retract_speed: 60
unretract_extra_length: 0
unretract_speed: 60

## Actual Results:
GUI Retraction Length displays as 0mm. GET_RETRACTION will return the correct value which proves this is likely just a cosmetic bug.

## Expected Results:
Retraction length should display 0.249.

## Additional information
retract_length: 0.25 and above will display correctly.

**Comment by StuSerious** [comment]
hey there @gregmatic!

thanks for spotting this, I think this was introduced in a recent update that had to do with those values directly
pretty safe to say you can expect a fix in the next releases!

have a nice day!
_~S_
