### ISSUE TITLE
Show the current power consumption in Sensortab

### ISSUE THREAD

**Issue by SaulGoodman1337** [fluidd-core/fluidd#368]
## Is your feature request related to a problem? Please describe.
I have a Shelly Power Plug S to which the printer is connected. 
With curl you can easily read out the current power consumption.

pi@klipper:~ $ curl -s -m 0.5 http://192.168.178.139/meter/0/power|jq .power
118.07

Now I would like to have a way to include this value in the Fluidd interface. Be it in the temperatures tab or whatever....

## Describe the solution you'd like:
It would be best if you could put somehow the sensor into the graph

## Describe alternatives you've considered:
I don't know... you decide

## Affected users and/or setups:
I find it quite interesting... also do not know why

## Additional Context:
(Add any other context or screenshots about the feature request here.)

**Comment by pedrolamas** [comment]
Indeed! Right now, Moonraker does not report any information in terms of power consumption, so we won't be able to do anything about it until that is also exposed there.
