### ISSUE TITLE
Problem displaying gcode thumbnail generated from Simplifi3D

### ISSUE THREAD

**Issue by doktorcb** [fluidd-core/fluidd#372]
I was looking for where the problem with the thumbnail is and why they don't appear, after a long time I discovered this.
There is no option to search for thumbnails in the "/home/pi/moonraker/moonraker/components/file_manager/metadata.py" configuration file for the S3D slicer. I copied this part from the Prusaslicer and copied it to the Simplifi3D part and everything works as it should. Please integrate this item permanently, there are enough fans who will appreciate this support.

**Comment by pedrolamas** [comment]
This is a Moonraker issue, not a Fluidd one, so you might want to open a ticket there instead!

Fluidd is just a frontend for the Moonraker API, so whatever Moonraker has available to use is what we will be able to show.
