### ISSUE TITLE
Internal error during connect: 'module' object has no attribute 'ProbePointsHelper'

### ISSUE THREAD

**Issue by valterjesus30** [fluidd-core/fluidd#374]
after doing an update, this error appeared out of nowhere, can anyone help me solve this problem 
![image](https://user-images.githubusercontent.com/85896355/127692003-b402889e-ecaa-4167-b02e-24fc81b356a3.png)

**Comment by Biorn1950** [comment]
For klipper related issue you can use the [discord](https://discord.gg/ctSg5BpB) or the [discourse](https://klipper.discourse.group/)
