### ISSUE TITLE
Can I install fluidd at other hardware，such as Allwin H6 with Armbian？

### ISSUE THREAD

**Issue by dgpower** [fluidd-core/fluidd#377]
Raspberry Pi is too expensive. I want to use a TV box to install fluidd. It uses the Allwinner H6 chip and runs an armbian system.

How can I manually install and run fluidd?

**Comment by nlef** [comment]
Maybe [kiauh](https://github.com/th33xitus/kiauh) may help

**Comment by dgpower** [comment]
谢谢！我现在确实是用这个脚本安装的。很方便！

可惜这个脚本其中一段还继续用Pythion2.7,。最好能改为Python3就完美了
----- 原始邮件 -----
发件人：nlef ***@***.***>
收件人：cadriel/fluidd ***@***.***>
抄送人：Special ***@***.***>,  Author ***@***.***>
主题：Re:_[cadriel/fluidd]_Can_I_install_fluidd_at_other_hardware，such_as_Allwin_H6_with_Armbian？_(#377)
日期：2021年08月06日 05点20分


Maybe kiauh may help

&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ainmimdal** [comment]
I installed fluidd on a rockhip tv box using kiauh. Installs fine

**Comment by pedrolamas** [comment]
Yes, you should be able to install in most recent Debian derivatives with little to no issues at all - and that includes Armbian!

Alternatively, if your system can run Docker, you can then just use the Docker image and run that!
