### ISSUE TITLE
Hot folder for uploading prints

### ISSUE THREAD

**Issue by buikpijn** [fluidd-core/fluidd#383]
## Is your feature request related to a problem? Please describe.
My request is to have watch folder in which i can directly upload my prints from the network. 

## Describe the solution you'd like:
I'd like a folder that is watched by fluidd in which gcode files are stored and the meta data is read so fluid shows the used slicer, layer thickness, etc.

## Describe alternatives you've considered:
I've used octoprint as an alternative, but do like fluid better. I've setup the smb function on the pi and used the virtual sd card folder as a dropfolder for my prints. It throws sd card busy errors and doesn't show metadata. 

## Affected users and/or setups:

I think everybody that prints using the same network can relate to the fact that it's not fantastic to upload every single print to the printer through the webinterface separately

## Additional Context:
I'm using s3d so i can't use the octoprint api spoofer meant for slic3r and such

**Comment by buikpijn** [comment]
If it existst i am worse in searching than i though.. I'm unable to find any information in regards to my request;

I'd like a watched folder where you can upload prints to.

I tried this through the standard virtual sd-card folder, creating a SMB share to put files in that folder, but Fluidd can't read the meta-data of files that are placed in there and it also threw an SD busy error.

I know there is a octoprint spoofer for uploading from slic3r, but s3d is my goto slicer.

**Comment by buikpijn** [comment]
How do you upload your prints? Always through the web-interface?

Thanks in advance for your response.

**Comment by matmen** [comment]
Requires support in [fluidd-core/FluiddPI ](https://github.com/fluidd-core/FluiddPI) for SMB shares first

**Comment by pedrolamas** [comment]
We have stopped supporting FluiddPi a long time ago, so this has gone outside of our scope - as Fluidd is just a web interface that runs on the client browser.

Having said that, Moonraker already monitors the `gcodes` folder (by default, `~/printer_data/gcodes``) and Fluidd will automatically show any new file that gets created there.

**Comment by pedrolamas** [comment]
One final note here I completely almost forgot: Fluidd support drag & drop of files AND folders directly to the browser (files will just be uploaded), so that might also be a nice way to go around this!
