### ISSUE TITLE
How to change default move axis distances preset?

### ISSUE THREAD

**Issue by int-0x03** [fluidd-core/fluidd#387]
<img width="339" alt="image" src="https://user-images.githubusercontent.com/42711898/129066936-3eb02e6e-8b3e-487d-9167-2379308d35d6.png">

I want to change this preset e.g. 0.1 1.0 10 25 50 100 because it's completely incompatible with my printer.

**Comment by Biorn1950** [comment]
That would be a good idea to add custom value like for the Z-offset

**Comment by pedrolamas** [comment]
@int-0x03 if you don't mind me asking, what printer do you have and what presets would you like to have there for your printer?
