### ISSUE TITLE
Target Temperatures for other temperature sensors

### ISSUE THREAD

**Issue by pacmac** [fluidd-core/fluidd#397]
Would it be possible to show the target temperatures for other temperatures, especially the chamber ?

A read only field would be fine, my chamber target temp is passed from the slicer to the start_print macro, and it would nice to be able to see what the target temp is as I wait for the chamber to reach a temp before continuing

Many Thanks

**Comment by sirjaymz** [comment]
+1

**Comment by pedrolamas** [comment]
Related to #434
