### ISSUE TITLE
Camera set up, more detailed instructions in help file

### ISSUE THREAD

**Issue by melfahn** [fluidd-core/fluidd#403]
The bolded line below is very confusing and it would save a ton of time for newbies like me wanting to make modifications if  this was detailed more completely. The raspberry pie camera is working, but I can't figure out where to set the resolution.  I'm sure it's very simple. webcam.txt doesn't appear to exist.  thanks!

Fluidd (and FluiddPI) has built in support for web cameras.

On older versions of FluiddPI (pre 1.15) you can edit the file found here; /boot/fluiddpi.txt.

**Versions of FluiddPI after 1.14 allow configuring your cameras from the same place as your other configuration files, and can be found in the webcam.txt file.**

**Comment by HaroldSP** [comment]
Hi!
You can set it like this^
camera_usb_options="-r 640x480"
