### ISSUE TITLE
Emergency Stop outside iPhone X/XR/XS/11/12 Safe Area

### ISSUE THREAD

**Issue by Kaiede** [fluidd-core/fluidd#405]
## Affected Version(s):
(The versions of fluidd this issue occurs on.)
- klipper version: 0.9.1-773-gc84956be
- moonraker version: 1.0.2-96-g2ab00c6
- fluidd version: 1.16.2

## Platform:
iPhone 12

## Hardware Configuration:
Pi 4B, Spider Board

## Reproduction Steps:
1. Browse to your fluidd instance on iPhone.
2. Use "Add to Home Screen"
3. Bring up the PWA now pinned to the home screen, and scroll down to the bottom.

## Actual Results / Screenshot:
![IMG_2225](https://user-images.githubusercontent.com/41651119/132737017-48a1d053-4049-424e-9b62-24a4c60a370e.PNG)

Version text overlaps the home bar. More importantly the emergency stop button is crammed into the very bottom corner, making it hard to hit. Since newer iPhones use rounded screens, the emergency stop is just starting to get clipped by the physical screen edge.

## Expected Results:
I'd expect the bottom of the scroll view to clear the home bar, but more importantly, the emergency stop button to be a little more reachable, and out of the "unsafe area" near the home bar.

## Log Files:
(The log files fluidd provides at Configure > System Control.)
- klipper log:
- moonraker log:

## Additional information
(Extra information relevant to the issue, links to similar issues.)

**Comment by Biorn1950** [comment]
Hello, thanks for the report.

We are going to check that soon.
