### ISSUE TITLE
FR: Config Backups (For all *.cfgs -- not just printer.cfg)

### ISSUE THREAD

**Issue by bad1dea** [fluidd-core/fluidd#413]
## Is your feature request related to a problem? Please describe.
I think the printer.cfg backup (with timestamp) feature should be implemented on all config files -- as most user cases now have split cfgs for more advanced klipper usage.

## Describe the solution you'd like:
Implement same printer.cfg backup/revision on all *.cfg files.

## Affected users and/or setups:
Users who have setup their klipper config files into individual files for easier editing/readability.

i.e 
printer.cfg -> stores all printer related variables/settings and loads other cfg files
cfgs/steppers.cfg -> stepper config
cfgs/extruder.cfg -> extruder config
etc

**Comment by Biorn1950** [comment]
> I think the printer.cfg backup (with timestamp) feature should be implemented on all config files -- as most user cases now have split cfgs for more advanced klipper usage.

Hello, from my experience only ratrig users have this kind of structure and it's a nightmare when they ask for help.

Anyway it's a good idea. I'll going to make the backup optional and add all the .cfg files.

**Comment by matmen** [comment]
Related: #311

**Comment by matmen** [comment]
Unsure about whether this is in scope for Fluidd or not. The printer.cfg backups are all created by Klipper. @StuSerious @pedrolamas opinions?
