### ISSUE TITLE
Support subdirectories

### ISSUE THREAD

**Issue by jdart** [fluidd-core/fluidd#423]
## Is your feature request related to a problem? Please describe.
I expose some web services through the same hostname, but in subdirectories like https://some.domain/service1/, https://some.domain/service2/

## Describe the solution you'd like:
I found I could make a semi working build of fluidd by setting publicPath in the vue config, but then the config.json was loaded from the root directory, and then I had to fiddle with apiUrl in localStorage... it would be nice if this worked out of the box.

## Describe alternatives you've considered:
I could use a subdomain.

## Affected users and/or setups:
This is a common pattern that others might already follow and it might make adoption easier.

## Additional Context:
n/a

**Comment by pedrolamas** [comment]
This is not something easy to add support for, it is just how the Vue framework (and others) works!

Adding a specific subfolder would require directly setting that at compile time and thus, it is something we will not be supporting ourselves.

It's a lot easier to add support for different ports or hosts, as that does not change from the root host - and for this you can just use any reverse proxy, such as Nginx.
