### ISSUE TITLE
[v1.16.2] Editing Z coordinate uses XY speed instead of Z speed (caution!!)

### ISSUE THREAD

**Issue by batista16** [fluidd-core/fluidd#427]
## Affected Version(s):
- klipper version: v0.10.0-39-g5f184e3f
- moonraker version: v0.7.1-67-gc631bff 
- fluidd version: v1.16.2

## Platform:
FluidPi on Rpi, using Chrome

## Reproduction Steps:
If you use the control arrows for Z, it uses the correct speed value configured in the "tool" section. If you change the Z coordinate in the position input boxes, it uses the XY speed instead of the Z speed. It's scary! 

## Expected Results:
Changing the Z coordinate should use the Z speed, no XY speed.

**Comment by Biorn1950** [comment]
Hello, I'm not able to reproduce this issue. can you share a screen of the console history and the settings please?
