### ISSUE TITLE
Implement a button to download your logs from the side panel  

### ISSUE THREAD

**Issue by GrzegorzManiak** [fluidd-core/fluidd#428]
Please add buttons to the side panel that allow you to download your klippy/moonraker logs, simple as that
![msedge_fEZObrRA2o](https://user-images.githubusercontent.com/83783716/137031971-cb2c3aef-ad2f-4ff8-ac86-d72dad77f084.png)

## Describe the solution you'd like:
A button that downloads the logs from klippy/moonraker to your device

## Describe alternatives you've considered:
SSH'ing into the machine which is a pain.

## Affected users and/or setups:
Anyone who is trying to troubleshoot their problems will benefit from this.

**Comment by Biorn1950** [comment]
Are you want to be able to upload a custom logo from your computer?

**Comment by Biorn1950** [comment]
You already have it here.
<img width="1030" alt="Capture d’écran 2022-01-29 à 23 50 19" src="https://user-images.githubusercontent.com/39673091/151680094-12bb0453-9fa4-473c-9376-a58eda044804.png">
