### ISSUE TITLE
v1.16.2-0fa3c9b - Speed reporting incorrectly

### ISSUE THREAD

**Issue by jasonhamilton** [fluidd-core/fluidd#429]
Not sure if this is a bug or a feature....  speed is reporting max speed of Gcode file not actual velocity.  In the gif below, the velocity from the API via web socket subscription are reporting on the left side, but the speed does not update in the GUI.

![Screen Recording 2021-10-13 at 6 10 17 PM](https://user-images.githubusercontent.com/388840/137233970-33a1cafb-74eb-472e-a55c-93ff0c297c79.gif)

## Affected Version(s):
v1.16.2-0fa3c9b

## Platform:
MailsailOS

## Hardware Configuration:
RPI

## Reproduction Steps:
NA

## Actual Results:
NA

## Screenshot(s):
See above

## Expected Results:
Reported speed should show instantaneous velocity, right?

## Log Files:
I can provide if needed...

## Additional information
na

**Comment by Biorn1950** [comment]
Hello, fluidd report the requested speed (which is in the gcode_move object) and not the live_velocity.
