### ISSUE TITLE
Save Changes that have been adjust during printing

### ISSUE THREAD

**Issue by acosano** [fluidd-core/fluidd#431]
## Is your feature request related to a problem? Please describe.
there sometimes changes in parameters during printing e.g. Z Offset, Speed, Flow etc.. that I may have to use the next time I  Switch on the printer I could recall them. At the moment  I write them down and then next day I just type it back in.

## Describe the solution you'd like:
Option to save and load previous settings.

## Describe alternatives you've considered:
No alternatives

## Affected users and/or setups:
Probably many users would like to have this as it saves time and no need to write it down or remember the settings to reuse .

## Additional Context:
(Add any other context or screenshots about the feature request here.)

**Comment by ChipCE** [comment]
A simple "hack" with macro. Put this in your config file and add AUTO_SAVE_CONFIG at the bottom of your end print gcode.

```
[gcode_macro AUTO_SAVE_CONFIG]
gcode:
    {% if printer.configfile.save_config_pending %}
        SAVE_CONFIG
    {% endif %}
```

**Comment by acosano** [comment]
> A simple "hack" with macro. Put this in your config file and add AUTO_SAVE_CONFIG at the bottom of your end print gcode.
> 
> ```
> [gcode_macro AUTO_SAVE_CONFIG]
> gcode:
>     {% if printer.configfile.save_config_pending %}
>         SAVE_CONFIG
>     {% endif %}
> ```

Thanks m8. This will definitely help a lot.
