### ISSUE TITLE
[1.16.2] No moonraker in docker container

### ISSUE THREAD

**Issue by jernejp21** [fluidd-core/fluidd#432]
## Affected Version(s):
(The versions of fluidd this issue occurs on.)
- fluidd version: 1.16.2

## Platform:
Docker on Raspberry Pi
Docker on Windows 10

## Hardware Configuration:
Raspberry Pi 2B
Windows 10 PC

## Reproduction Steps:
1. Download image from [docker hub](https://hub.docker.com/r/cadriel/fluidd)
2. Use docker cli command to run the image in new container. Change -p parameter to `-p 3000:80`. To avoid conflict between service running on host and docker service.
3. Open fluidd's docker instance in browser - http://localhost:3000/

## Actual Results:
You will see no mooraker connection error

## Expected Results:
Fluidd should be running in a same manner as started from host machine.

## Additional information
There is also probably missing Klipper service. If I `docker exex -u root fluidd /bin/sh` and search files and folders, I cannot find moonraker and klipper folder anywhere.

**Comment by Vhab** [comment]
Moonraker's repository links to https://github.com/mkuf/prind

Fluidd doesn't always need to run on the same machine as Moonraker.
It makes sense for the docker image to not contain moonraker, as you could start a separate container for moonraker and klipper.
