### ISSUE TITLE
Display HTU21D humidity sensor data in the dashboard and graph

### ISSUE THREAD

**Issue by samwiseg0** [fluidd-core/fluidd#434]
## Is your feature request related to a problem? Please describe.
Yes and no. The problem is that Fluidd does not display the humidity of a HTU21D sensor. It only displays the temperature.

## Describe the solution you'd like:
The HTU21D sensors to show the current humidity level in the dashboard. Secondarily, it would be great if the the Humidity could be added to the graph/chart. 

## Describe alternatives you've considered:
Mainsail does show the humidity in the dashbaord.

## Affected users and/or setups:
Everyone using HTU21D sensors with Klipper

## Additional Context:
NA

**Comment by pedrolamas** [comment]
Fluidd is a client web app, so only shows what [Moonraker](https://moonraker.readthedocs.io/) (the server side API) exposes.

For this to work in Fluidd, you will first need to get Moonraker to implement this functionality; before that, there is nothing we can do about it here.

Closing for now, please feel free to reopen if situation in Moonraker changes!

**Comment by samwiseg0** [comment]
@pedrolamas Thank you for taking a look. I am a bit confused because it is possible in the mainsail interface? If moonraker cannot provide this information then they would also not be able to display this information?

I understand that the graph information is provided with websockets and moonraker would have to provide that information in the payload. 
<img width="737" alt="Screen Shot 2022-02-17 at 6 50 34 PM" src="https://user-images.githubusercontent.com/2241731/154591307-409cba50-6248-48c3-879a-14c65a7a2822.png">


But I still think it should be able to be part of the main interface much like mainsail?



I am not very familiar with the mainsail code base. I tried to look around and this is what I found. https://github.com/mainsail-crew/mainsail/blob/04b6992f3c202634948ee7c6afa9cd2c517f7af9/src/store/printer/getters.ts#L307-L339

**Comment by pedrolamas** [comment]
Apologies @samwiseg0, I was not aware of this and seems I spoke too soon... Thank you for following up and providing the correct way to retrieve this value.

I'm reopening this now and we will take a proper look into this on the first chance we get!
