### ISSUE TITLE
Invalid path request, 'config//.git'' is outside root 'config'

### ISSUE THREAD

**Issue by jLynx** [fluidd-core/fluidd#435]
## Affected Version(s):
(The versions of fluidd this issue occurs on.)
- klipper version: v0.10.0-66-g5c10001b
- moonraker version: v0.7.1-76-g6a6422c
- fluidd version: v1.16.2
- v-coreos version: v0.2.0-51-g9ca331a

## Platform:
Chrome (But this is NA)

## Hardware Configuration:
Pi 4 connected to BTT SKR Pro 1.2 (But again, NA)

## Reproduction Steps:
Version 1: 
1. Boot, connect to fluidd

Version 2: 
1. Check for updates on fluidd

## Actual Results:
The message `Invalid path request, 'config//.git'' is outside root 'config'` shows up in an error alert toast

## Screenshot(s):
![image](https://user-images.githubusercontent.com/4393979/137794734-519e472b-4188-4f9f-b88c-ec9a513c6091.png)

## Expected Results:
This should not show up at all.

## Log Files:
(The log files fluidd provides at Configure > System Control.)
- klipper log: 
[klippy.log](https://github.com/cadriel/fluidd/files/7368026/klippy.log)

- moonraker log:
[moonraker.log](https://github.com/cadriel/fluidd/files/7368027/moonraker.log)

## Additional information
This seems to be happening on every boot and whenever I search for updates.

**Comment by miklschmidt** [comment]
Worth noting that the .git folder is there because V-CoreOS uses a modular config updatable through moonraker (ie. its a git repository).

**Comment by miklschmidt** [comment]
@jLynx properly because of the extra forward slash.

**Comment by jLynx** [comment]
> @jLynx probably because of the extra forward slash.

That's what I was thinking as well. But I am unsure on where its coming from

**Comment by Arksine** [comment]
FWIW, a recent commit to Moonraker should prevent the "outside root" error.  That said I would still recommend that clients attempt to send normalized paths (ie: config/.git rather than config//.git).  Also, now that Moonraker sends notifications for hidden files you may want to have fluidd ignore those.

**Comment by Arksine** [comment]
Also, and this is JMO, it isn't a great idea to have the config path also be a git repo.  If you switch branches its possible that it will confuse inotify.

**Comment by miklschmidt** [comment]
@Arksine it won’t change branch, it’s managed through moonraker. The modular updatable config is pretty essential to RatOS (previously known as V-CoreOS). Sorry for abusing your project 😅 but so far it’s helped hundreds of new klipper users get their printers printing without having to even touch a cli 🙂

**Comment by Arksine** [comment]
Ah, makes sense.  To be honest I haven't tested inotify with a git repo so I'm not sure how it would behave.  If your users aren't having any problems with it then it sounds like its fine.

**Comment by miklschmidt** [comment]
@Arksine no issues so far! Well except for this one :) mainsail does it correctly.

**Comment by zenturacp** [comment]
> FWIW, a recent commit to Moonraker should prevent the "outside root" error. That said I would still recommend that clients attempt to send normalized paths (ie: config/.git rather than config//.git). Also, now that Moonraker sends notifications for hidden files you may want to have fluidd ignore those.

Well to be hones.. /config/////Folder2/Folder3 is the same as /config/Folder2/Folder3.. - though its bad practice its the same path.. And should be as valid..
![image](https://user-images.githubusercontent.com/37262317/139642591-e35f0175-86c4-4265-8d76-b9f63cd20122.png)

**Comment by Arksine** [comment]
Right, in the recent patch I make sure to normalize the path before processing it.   Previously it assumed that that path it receives in the API call would be normalized.
