### ISSUE TITLE
Thermals Chart is empty

### ISSUE THREAD

**Issue by Greendumb** [fluidd-core/fluidd#450]
## Affected Version(s):
- klipper version: v0.10.0-157-g05a8aca0
- moonraker version: v0.7.1-167-g4e8e4f7
- fluidd version: v1.16.2

## Platform:
The problem occurs on all platforms I use: desktop (win 10 all browsers), smartphone (iOS 15) etc

## Hardware Configuration:
Raspberry Pi 4 Model B

## Reproduction Steps:
Installed on a clean distribution Raspberry Pi OS via KIAUH
Tried to install twice from scratch, but it did not work

## Actual Results:
There is no result, Thermals Chart is also empty

## Screenshot(s):
![2021-11-22 08_52_07-fluidd _ Dashboard - Opera](https://user-images.githubusercontent.com/79982167/142819968-ad93dca9-c17c-4aa3-8b75-83a36233d8e0.png)

![2021-11-22 10_43_09-fluidd _ Dashboard - Opera](https://user-images.githubusercontent.com/79982167/142822281-48ae5d95-511b-4e11-94b5-d21b1cefcfd5.png)

## Log Files:
- klipper log: [klippy (8).log](https://github.com/fluidd-core/fluidd/files/7578986/klippy.8.log)
- moonraker log: [moonraker (1).log](https://github.com/fluidd-core/fluidd/files/7578989/moonraker.1.log)

## Additional information
On Mansail interface, the Thermals Chart displays well, but I like the Fluidd ;)

**Comment by Afterschnitzel** [comment]
Same here. It was caused by updating moonraker.

**Comment by DonyBerserker** [comment]
Same here, after update moonraker

**Comment by Greendumb** [comment]
The latest moonraker update (v0.7.1-169-g50fd8c9) solved the problem

**Comment by hieppo** [comment]
Unfortunately, v0.7.1-169-g50fd8c9 does not solve the issue. I have updated to currently v0.7.1-173-gccb86ea and the thermal chart are not displaying.
