### ISSUE TITLE
Fluidd on ArchLinux Manjaro

### ISSUE THREAD

**Issue by jccf07** [fluidd-core/fluidd#459]
Hi, I am need using fluidd, I try to install it by using Kiauh, but I use a Linux distribution based on ArchLinux (Manjaro) an it is not possible to use kiauh, because it Try to install package using apt-get. It is possible to install dependences manually. I could use snap or pacman 

Thanks!!

**Comment by anonizmous** [comment]
https://aur.archlinux.org/packages/fluidd-git/
