### ISSUE TITLE
h264

### ISSUE THREAD

**Issue by azytzn** [fluidd-core/fluidd#461]
## Is your feature request related to a problem? Please describe.
All about mpeg streamer. Frame rate very slow with pi-cam. 

## Describe the solution you'd like:
I recently did some research on h264 and found the github project named "pi-h264-to-browser" [https://github.com/dans98/pi-h264-to-browser](url). It works very well.  Instead of mpeg-streamer, h264 to browser will make Fluidd much more better.

## Describe alternatives you've considered:
-

## Affected users and/or setups:
-

## Additional Context:
-

**Comment by dragonnn** [comment]
Please take a look https://github.com/fluidd-core/fluidd/pull/425
Also, you might be interested in https://gitlab.com/dragonn/h264rcam with works even better for me
