### ISSUE TITLE
white page after rpi on / off

### ISSUE THREAD

**Issue by davevo22** [fluidd-core/fluidd#462]
Hi, yesterday after turning off RPI and turning it back on I see only the white website. The printer is connected to a klipper, I just can't control it through a website. It happened to me once and I had to reinstall the whole klipper and fluid. Any possible cause?
![image](https://user-images.githubusercontent.com/36174913/147340126-c5da8684-ab43-4377-a60d-29f643a3f394.png)

**Comment by StonikM** [comment]
I have the same problem, has it been fixed somehow?

**Comment by Biorn1950** [comment]
Hello,
You can use the [Klipper discord](https://discord.gg/eEZr8Qvc) or the [Fluidd discord](https://discord.gg/ccF72ypK) to find help about your issue.

Biorn
