### ISSUE TITLE
Cannot use Chinese as gcode file name

### ISSUE THREAD

**Issue by clementatt** [fluidd-core/fluidd#463]
## Affected Version(s):
(The versions of fluidd this issue occurs on.)
- klipper version:v0.10.0-215-g9bdd6175
- moonraker version:v0.7.1-280-g9d7baa1
- fluidd version:v1.16.2

## Platform:
I use Windows 11 21H2 and Chrome 96.0.4664.110
## Hardware Configuration:
I use Raspberry Pi 4B 2G as the host computer and mks gen_l v2.1 （mega2560）as the main board of the 3D printer.

## Reproduction Steps:
after I upgraded to v1.16.2 version, there was a problem that Chinese could not be used as the gcode file name.
## Actual Results:
(What happens after the reproduction steps have been followed.)

## Screenshot(s):
![image](https://user-images.githubusercontent.com/44233232/147760925-8c3002a7-5c27-42d3-a00b-439c2433123d.png)
![image](https://user-images.githubusercontent.com/44233232/147760934-8384b8a0-8a94-442b-8d74-385eeda579f4.png)
![image](https://user-images.githubusercontent.com/44233232/147760935-08a4c1ef-fc6d-4c0b-b4a0-b0b39affa387.png)

## Expected Results:
(What *should* happen after the reproduction steps have been followed.)

## Log Files:
(The log files fluidd provides at Configure > System Control.)
- klipper log:
[klippy.log](https://github.com/fluidd-core/fluidd/files/7793339/klippy.log)

- moonraker log:
[moonraker.log](https://github.com/fluidd-core/fluidd/files/7793340/moonraker.log)

## Additional information
(Extra information relevant to the issue, links to similar issues.)

**Comment by sjqlwy** [comment]
https://mc.dfrobot.com.cn/thread-311545-1-1.html?fromuid=725344

**Comment by BastelKlug** [comment]
I think the problem is with klipper or moonraker and not with fluidd.

**Comment by Biorn1950** [comment]
Hello,

For Klipper related issue, you can use the [Klipper discord](https://discord.gg/ctSg5BpB) or the [Klipper discourse](https://klipper.discourse.group/)

- Biorn
