### ISSUE TITLE
ESP32 cam as wifi ip cam for fluidd??

### ISSUE THREAD

**Issue by tnap1979** [fluidd-core/fluidd#465]
Hey,
I have a ESP32 cam, a few of em..
And I'd like to be able to use them as wifi ip cams in fluidd... is this even possible??
All I have is an ip address and it streams thru an interface
![Screenshot_20220102-175452_Chrome](https://user-images.githubusercontent.com/1660801/147892265-50dff481-2af6-4d58-8235-e1efd4b4f35c.jpg)

**Comment by BastelKlug** [comment]
Have you tried this? https://docs.fluidd.xyz/features/cameras

**Comment by tnap1979** [comment]
I have, and all I got was no display when I entered my ip address of the esp32 cam in there

**Comment by Biorn1950** [comment]
Hello,
For webcam related issue you can use the [Klipper discord](https://discord.gg/eEZr8Qvc) or the [Fluidd discord](https://discord.gg/ccF72ypK)

Biorn.
