### ISSUE TITLE
Fluidd v1.16.2 deleting jobs when selecting all but one object

### ISSUE THREAD

**Issue by stevereno30** [fluidd-core/fluidd#466]
## Affected Version(s):
(The versions of fluidd this issue occurs on.)
- klipper version: v0.10.0-185-gdebcc22f
- moonraker version: v0.7.1-253-g3e70e4b 
- fluidd version: v1.16.2 

## Platform:
Firefox, Windows 11

## Hardware Configuration:
RaspPi 3B, BTT Octopus

## Reproduction Steps:
1. Select jobs/folders with the checkboxes until only one remains unchecked.

## Actual Results:
The final box is automatically selected.

## Screenshot(s):
![index](https://user-images.githubusercontent.com/5103600/148129425-a3d49dcb-f19a-4a29-83ce-3949bda7f033.gif)

## Expected Results:
The final box should remain unchecked.

## Log Files:
(The log files fluidd provides at Configure > System Control.)
- klipper log: [klippy.log](https://github.com/fluidd-core/fluidd/files/7810617/klippy.log)

- moonraker log: [moonraker.log](https://github.com/fluidd-core/fluidd/files/7810619/moonraker.log)

**Comment by BastelKlug** [comment]
Hello, I have tried to reproduce your bug with the newest fluidd dev version (1.7.0). Maybe it was fixed. 

Sorry for the bad quality:
![Video](https://user-images.githubusercontent.com/44060099/148695955-eab696f4-6ac8-411b-96df-3a6a54a5bf46.gif)

**Comment by BastelKlug** [comment]
I have found the PR which fixes this Bug: https://github.com/fluidd-core/fluidd/pull/443
