### ISSUE TITLE
CANCEL_PRINT not accepted in Fluidd.cfg

### ISSUE THREAD

**Issue by pgale** [fluidd-core/fluidd#468]
## Affected Version(s):
(The versions of fluidd this issue occurs on.)
- klipper version: v0.10.0-223-g4c8d24ae
- moonraker version: v0.7.1-285-g505c1bf
- fluidd version: v1.16.2

## Platform:
(Information about your platform, like the OS or browser you are using.)
Raspberry Pi 4

## Hardware Configuration:
(Information about your hardware configuration. Like MCU, host and setup)
Ender 3 v2 4.2.2

I keep getting the 'CANCEL_PRINT macro not found in configuration.' error if I remove the CANCEL_PRINT macro from printer.cfg and add it to Fluidd.cfg

Docs seem to suggest (but not clear) that Fluidd.cfg holds this macro. Does some version also need to be in the Printer.cfg and if so, who takes precedence?

**Comment by BastelKlug** [comment]
did you include the Fluidd.cfg with [include Fluidd.cfg]?

**Comment by pgale** [comment]
Should that go in printer.cfg?
I’ve not done that if so

**Comment by BastelKlug** [comment]
Yes you have to do that because with that external file you are expand the printer.cfg

**Comment by pgale** [comment]
Thanks - will try that.
