### ISSUE TITLE
v1.16.2 When printer is not connected cameras cannot be selected

### ISSUE THREAD

**Issue by RobRobM** [fluidd-core/fluidd#470]
I have 2 cameras, one pi camera and one USB webcam, connect and when the printer is offline I cannot switch cameras. I can only use the camera pull down menu when the printer is connected. If the cameras are visible when the printer is online that they will remain visible when the printer goes offline.

## Affected Version(s):
(The versions of fluidd this issue occurs on.)
- klipper version: v0.10.0-221
- moonraker version: v0.7.1-280
- fluidd version: v1.16.2

## Expected Results:
Able to switch cameras anytime.

**Comment by pedrolamas** [comment]
This is now fixed in the `develop` branch and will be available on the next release!
