### ISSUE TITLE
how much filament is left on the spool

### ISSUE THREAD

**Issue by bulbersator** [fluidd-core/fluidd#471]
Hi, 

## Is your feature request related to a problem? Please describe.
It is difficult to say how much filament is left on the spool. Fluidd has fairly accurate information on how much filament has been used. This will allow to determine whether there is enough filament for the next print.

## Describe the solution you'd like:
I am thinking about a function or an add-on for fluidd so that I can enter information about a new filament spool (preferably weight of the spool which would be calculated into its length, or length), and then the fluidd calculates how much filament is left on the spool based on the printed files. It could also display a warning if there might not be enough filament on the spool for the printout. 
There should be a function to insert new spool and information about it (type of material, weight)

## Describe alternatives you've considered:
Pausing during printing to replace the filament is troublesome and can cause problems.

## Affected users and/or setups:
Everyone :)

**Comment by Biorn1950** [comment]
Hello, when a spool manager module will be integrated in moonraker that will be available in fluidd.

- Biorn
