### ISSUE TITLE
force_move toggle

### ISSUE THREAD

**Issue by Biorn1950** [fluidd-core/fluidd#494]
Adding a slider in the toolhead card if the force_move is allowed to freely move the toolhead for maintenance usage.

**Comment by pedrolamas** [comment]
This sounds interesting and I think we should take a look into it, but how would this really work? What commands would we be sending to Klipper?

**Comment by matmen** [comment]
> This sounds interesting and I think we should take a look into it, but how would this really work? What commands would we be sending to Klipper?

FORCE_MOVE is the command you're looking for 😉

**Comment by pedrolamas** [comment]
Given this most likely will put the printer in an incorrectly homed stat, I wonder if it would make more sense to have it on the "Tune" panel instead of the main one?

**Comment by matmen** [comment]
I think this would make sense if the printer isn't homed at all, with big warnings telling users that it's a bad idea and may physically break the printer. Maybe a checkbox (or a button to toggle until next home) in a menu in the tool card header that just enables the movement arrows?
