### ISSUE TITLE
Layer count is wrong when printing multiple object with "complete individual objects" enabled in Super Slicer

### ISSUE THREAD

**Issue by RobRobM** [fluidd-core/fluidd#501]
### What happened

I have printed multiple projects from Super Slicer today with 2 or more object completed individually and the layer count is wrong for all but one object.
![layercount](https://user-images.githubusercontent.com/19664209/151881984-9d7c2e53-c984-4915-b4a9-cebeb28b5709.png)
.

### What did you expect to happen

See the layer count of each individual object or the total number of layers of all object combined.

### How to reproduce

Slice multiple objects in Super Slicer with "complete individual objects" enabled, print and watch the layer count.

**Comment by Biorn1950** [comment]
Hello, I think the total combination is the way to go.

**Comment by RobRobM** [comment]
I second that.

**Comment by pedrolamas** [comment]
Arguably, we might want to look into not only showing the current and total layers, but also the current and total number of objects to print!

**Comment by pedrolamas** [comment]
@RobRobM can you provide the gcode so we can repro this issue?
