### ISSUE TITLE
No "HTTP page" option in the dropdown list when adding a camera

### ISSUE THREAD

**Issue by xyzroe** [fluidd-core/fluidd#508]
### What happened

When trying to add a new camera, there is no "HTTP page" option in the dropdown list of camera types
![1](https://user-images.githubusercontent.com/6440415/152392140-c1591020-81b5-4bc7-8544-7fb2fd12c77d.jpeg)

### What did you expect to happen

Accordingly to #425, there should be such a possibility.

### How to reproduce

Just install fresh fluidd (v1.16.2) and try
![2](https://user-images.githubusercontent.com/6440415/152391441-fbd9361d-c02d-4b43-b4cd-a876fb4af178.jpeg)

### Additional information

I have looked at the current code in the repository, namely
https://github.com/fluidd-core/fluidd/blob/003c25a661d87872918979aedad4711ddf6327ce/src/components/settings/cameras/CameraConfigDialog.vue#L70
https://github.com/fluidd-core/fluidd/blob/003c25a661d87872918979aedad4711ddf6327ce/src/components/settings/cameras/CameraConfigDialog.vue#L108
https://github.com/fluidd-core/fluidd/blob/003c25a661d87872918979aedad4711ddf6327ce/src/components/widgets/camera/CameraItem.vue#L26
https://github.com/fluidd-core/fluidd/blob/003c25a661d87872918979aedad4711ddf6327ce/src/store/cameras/types.ts#L10
and I see that all additions are present, they have not been removed, it seems to me that everything should work.
But I don't have this option.
Please let me know if the problem is on my side.

**Comment by matmen** [comment]
https://github.com/fluidd-core/fluidd/commit/ec6ab043deabc75a71d5772e4d0a97e3c01614a0 landed in develop in November, but the last Fluidd release was in July. It'll be shipped with the next release; if you need it sooner you can either use [the dev app](http://dev-app.fluidd.xyz/) or build/deploy the develop branch yourself.
There's no ETA for [Fluidd v1.17](https://github.com/fluidd-core/fluidd/milestone/2) yet, but it should be out soon.

**Comment by xyzroe** [comment]
Oh, thank you very much. 
I completely forgot to check the branches.
I'll try to install the developer branch
