### ISSUE TITLE
Chrome/Brave title bar color in "app mode" doesn't update/match selected theme color

### ISSUE THREAD

**Issue by millerlarson** [fluidd-core/fluidd#515]
### What happened

When in Chrome/Brave you can:
Menu > More Tools > Create Shortcut > Open As Window

![create shortcut](https://user-images.githubusercontent.com/7883766/152937611-1d845a7d-d2fe-4292-964d-02a748c49859.png "create shortcut")
![open as window](https://user-images.githubusercontent.com/7883766/152937647-dd2c27c0-5ef8-4ad1-83b6-a5ddc15d375d.png "open as window")

When doing so, the title bar of the window seems to be staying the default color and not updating with the selected theme value.

Here is a screenshot showing the title bar seemingly default **BLUE** from fluidd, when the selected theme color is **RED**:

![titlebar color screenshot](https://user-images.githubusercontent.com/7883766/152937678-32e78a95-beb4-47df-b68e-6e3ac12673a3.jpg "title bar color")

### What did you expect to happen

I would hope that the color of the title bar changes to match the selected theme as so many other parts of the UI do.

### How to reproduce

1. Change theme color to something non-default
2. Make a Chrome/Brave "App/Shortcut"
3. Observe color of title bar

### Additional information

I could be wrong, but this doesn't seem to be coming from the browser, or the OS (Windows 10) theme.  If this isn't coming from fluidd, I apologize for the noise.

(edited for some clarity)

**Comment by pedrolamas** [comment]
Fluidd is a Vuejs app, but currently it is lacking the manifest that would allow those colors (and other stuff like icons) to be used as a "native" app.

We will keep this in mind and look into implementing it in the near future (unless someone goes ahead and contributes a PR for it 😉 )
