### ISSUE TITLE
Gcode live view not working for circular bed (delta printer)

### ISSUE THREAD

**Issue by yzheka** [fluidd-core/fluidd#519]
### What happened

Gcode live view is empty when using on detla printer but it is working good on rectangular bed. I guess it is because of round bed have origin at 0;0
![image](https://user-images.githubusercontent.com/5080736/153616986-cf058218-9df2-4732-a900-4f0b8373cc7e.png)

### What did you expect to happen

Gcode live view is visible when using round bed

### How to reproduce

Start any print on delta printer and load current file to gcode live view

**Comment by Mechazawa** [comment]
I sadly don't own a delta printer nor do I have a slicer set up for one. Could you share some gcode for testing?

**Comment by yzheka** [comment]
@Mechazawa
[test_cube.zip](https://github.com/fluidd-core/fluidd/files/8119570/test_cube.zip)
Here. I have sliced test cube with cura using my regular settings
