### ISSUE TITLE
Readme update images

### ISSUE THREAD

**Issue by ReinBentdal** [fluidd-core/fluidd#539]
### What happened

The current images in readme.md does not represent the current UI design of Fluidd. I probably speak on behalf of many when I say that initial impressions are quite important when choosing klipper frontend. I would therefore suggest updating the images to represent the current state of Fluidd UI.
It also enhances the impression of a quality product, in my opinion.

### What did you expect to happen

Excepted updated images

### How to reproduce

develop/readme.md

### Additional information

Kudos to the developers which is keeping this project alive!

**Comment by matmen** [comment]
This is the goal of #537
Are there any other screenshots you noticed need an update?
