### ISSUE TITLE
Display the name of the printer in the header AND the browser tab

### ISSUE THREAD

**Issue by andremalenfant** [fluidd-core/fluidd#580]
### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

It would be nice to be able to quickly identify which printer we are connected to. The name could be display in lieu of the word "Fluidd" on the top of the page and on the browser tab. Or next to it.

**Comment by pedrolamas** [comment]
This is already the default, all you need to do is go to `Settings` and change the `Printer Name` for whatever you want and that will be the shown on the browser tab!
