### ISSUE TITLE
Feature Request: Full-Screen Console

### ISSUE THREAD

**Issue by matthewlloyd** [fluidd-core/fluidd#598]
### Is your feature request related to a problem? Please describe

The console panel on the Home tab can sometimes be a little too small, especially when viewing large numbers of log lines, or log lines that are particularly long.

### Describe the solution you'd like

It would be nice to have a full-screen console tab accessible by clicking a button on the left-hand navigation bar.

**Comment by pedrolamas** [comment]
Sounds interesting! I think a separate page accessible via left-hand navbar for this would be a useful addition! 🙂
