### ISSUE TITLE
How to connect 2 printer into one pi?

### ISSUE THREAD

**Issue by Timoraty** [fluidd-core/fluidd#617]
### Browser

Edge

### Device

Laptop

### Operating System

Windows

### What happened

I'm using Raspberry pi 4B to connect 2 Anycubic Mega S and trying to control them, but I can only control one printer at the time, unless I change the serial port from USB0 to USB1. and the official doc is confusing, the moonraker is a mass, I tried to add a new cors_domains and the moonraker will just not be connect at all.

### What did you expect to happen

Get it work

### How to reproduce

I don't know

### Additional information

BTW I'm not from this net working profession.

**Comment by lordIcocain** [comment]
You need another one instance of klipper service and moonraker service. Easiest way to setup is "kiauh" script.
https://github.com/th33xitus/kiauh
Then just add another printer in web interface using pi ip and port of new moonraker service.

**Comment by Timoraty** [comment]
> You need another one instance of klipper service and moonraker service. Easiest way to setup is "kiauh" script. https://github.com/th33xitus/kiauh Then just add another printer in web interface using pi ip and port of new moonraker service.

I installed the "kiauh" but when I selected install-->Klipper the system warning "At least one Klipper service is already installed:  ➔ /etc/systemd/system/klipper.service"

**Comment by lordIcocain** [comment]
> 

As many as you like (until there resources PI enough), when you choose to install another klipper/moonraker you will be warned that it is already installed, but after that it should offer to change name of new service, for example klipper1, klipper2 etc. then installing should be sucless.

**Comment by Timoraty** [comment]
> > 
> 
> As many as you like (until there resources PI enough), when you choose to install another klipper/moonraker you will be warned that it is already installed, but after that it should offer to change name of new service, for example klipper1, klipper2 etc. then installing should be sucless.

when I switch to scurve-shaping or smoothing, and I selected install klipper this warning come up 
" At least one Klipper service is already installed:
 ➔ /etc/systemd/system/klipper.service"

**Comment by Timoraty** [comment]
> > 
> 
> As many as you like (until there resources PI enough), when you choose to install another klipper/moonraker you will be warned that it is already installed, but after that it should offer to change name of new service, for example klipper1, klipper2 etc. then installing should be successful.

it didn't offer me to change name for services

**Comment by lordIcocain** [comment]
For example https://youtu.be/wJHcsUcfsQA
maybe need reinstall klipper, dont forgot to make backup of configs.

**Comment by lordIcocain** [comment]
Did you succeed?

**Comment by Timoraty** [comment]
> Did you succeed?

I've been assign on other project,  I will to try that in next day. still great, thanks for the advise

**Comment by Timoraty** [comment]
> Did you succeed?

It works! Huge thanks to all of you.
