### ISSUE TITLE
Same as here: Webcam Window is Tiny #371 

### ISSUE THREAD

**Issue by homuser2003** [fluidd-core/fluidd#625]
### Browser

Edge

### Device

Laptop

### Operating System

Windows

### What happened

Both in Edge and Chrome - The webcam is appearing only collapsed on the dashboard but works fine when I click on the fullscreen button. The solution described here "Webcam Window is Tiny #371" does not seem to work for me. See config files below. Thanks!

Camera ist identified by lsusb as: Bus 001 Device 005: ID 0bda:2137 Realtek Semiconductor Corp. Web Camera

[matmen: removed printer.cfg for sanity, irrelevant to the issue]

### What did you expect to happen

A small Window showing the livestram from the webcam on the Dashboard

### How to reproduce

Just opening Fluidd with webcam plugged in and working

### Additional information

![image](https://user-images.githubusercontent.com/77500963/162563656-14dedf0e-ecf9-4549-89f1-c4fa9efb6f13.png)

**Comment by matmen** [comment]
This is caused by fluidd not being able to access the webcam. What URL are you using to access it? Can you post a screenshot of your camera settings (in the fluidd UI)?

**Comment by homuser2003** [comment]
![image](https://user-images.githubusercontent.com/77500963/162578368-5cadaf5e-3081-4d8b-9488-1434e435c68e.png)

Sure! Thanks for your help!

**Comment by matmen** [comment]
Append a `/?action=stream` to the URL and make sure you can access it from your browser

**Comment by homuser2003** [comment]
You made my day! Makes perfect sense once I thing about it :-)

Thanks!

![image](https://user-images.githubusercontent.com/77500963/162578996-d2ff59ff-ad8d-4cf0-ab6f-6302bcc229ea.png)

**Comment by matmen** [comment]
no problem!
