### ISSUE TITLE
Installation instructions are missing.

### ISSUE THREAD

**Issue by iblue** [fluidd-core/fluidd#626]
### Browser

Other (Please tell us below)

### Device

Other (Please tell us below)

### Operating System

Other (Please tell us below)

### What happened

It says "Manual configuration steps are coming soon."

### What did you expect to happen

I expected to get instructions on how to install fluidd on Debian (bare metal, no dockers).

### How to reproduce

1. Go to https://docs.fluidd.xyz/installation/manual.

### Additional information

The issue is not dependent on the browser, device and operating system.

**Comment by matmen** [comment]
Duplicate of https://github.com/fluidd-core/fluidd/issues/299
