### ISSUE TITLE
Why didn't the configuration save and restart?

### ISSUE THREAD

**Issue by ghost** [fluidd-core/fluidd#638]
### Is your feature request related to a problem? Please describe

In the past, there was a shortcut to save and restart at the top of the version configuration. It is very convenient to save and restart once you modify the parameter points. But now the version has not been saved and restarted, only one is saved. After saving, you have to go back to the system and restart FIRMWARE. It's too much trouble to click. . .

### Describe the solution you'd like

I hope to add a shortcut to save and restart at the top of the configuration

### Additional information

fluidd v1.17.2
klipper v0.10.0-376

**Comment by Cloud2702** [comment]
Look, edit printer.cfg I don't know why I only have a save here, but I don't save it and restart it.

**Comment by Cloud2702** [comment]
![QQ截图20220422094704](https://user-images.githubusercontent.com/85711992/164581058-36ec3309-b937-4b1a-9dc8-73d1b8bd59d9.png)
Look, edit printer.cfg I don't know why I only have a save here, but I don't save it and restart it.

**Comment by pedrolamas** [comment]
The only reason I could see for this to happen is if the service is not called "klipper".

On the main window, click the vertical "..." on the top right, then expand "Services", take a screenshot of that and share it here please!

Here's an example of mine:

![image](https://user-images.githubusercontent.com/85504/164709126-f4b99e0f-471f-4ad0-88b9-404c229b3dbf.png)

**Comment by Cloud2702** [comment]
![111](https://user-images.githubusercontent.com/85711992/164823183-a8ad6568-cf5a-4147-8fd5-068d61bf6c06.png)
With two machines, is the screenshot like this?

**Comment by pedrolamas** [comment]
That's exactly it, and confirms what I suspected: as you have 2 Klipper instances, we don't actually know which one to restart when you save the file, hence why you don't see the "Save and Restart" button.

**Comment by Cloud2702** [comment]
So install a klipper is able to see, and then install two klipper is not visible, is the reason for saving the file? Can we also solve the problem of saving and restarting with N machines or klipper in the future?

**Comment by pedrolamas** [comment]
Fluidd is just a web interface, so all we can do is what the server (Moonraker) allows us to do. When only a Klipper instance exists, we can safely restart it as it is a single instance, but if multiple exist, we have no way of knowing directly which one is that config file referring to.

In any case, the solution for this will have to come from Moonraker first.

**Comment by Cloud2702** [comment]
ok, thanks for the reply

**Comment by pedrolamas** [comment]
I'm reopening this as Moonraker now supplies the correct service names so we can now restart the correct service!
