### ISSUE TITLE
How can I add my own function in web page?

### ISSUE THREAD

**Issue by Terbinm** [fluidd-core/fluidd#643]
![image](https://user-images.githubusercontent.com/80260085/164984462-3a95b8ad-1612-4cee-b1b3-d77c15c732d5.png)

if I can add my own function in web page?? and which file?

**Comment by matmen** [comment]
Hi, what kind of function would you like to add?
For custom logic you will need to set up your own dev instance as described in https://docs.fluidd.xyz/development
The required files for the file browser are in `src/components/widgets/filesystem`

**Comment by Terbinm** [comment]
The discord channel inside,I just use camera function and another server to
do it.

**Comment by Terbinm** [comment]
The discord channel inside,I just use camera function and another server to do it. 
![image](https://user-images.githubusercontent.com/80260085/164987324-a76e034a-71e1-46ce-a307-ac92cd6116b0.jpeg)

Thank a lot.

**Comment by matmen** [comment]
This isn't something we want to support natively because of performance concerns. However, you are free to set up your own fluidd build and add an `<iframe>` onto the dashboard. Help for setting up a dev instance is described here: https://docs.fluidd.xyz/development
