### ISSUE TITLE
Display or configure nozzle size from main UI?

### ISSUE THREAD

**Issue by thisiscam** [fluidd-core/fluidd#647]
### Is your feature request related to a problem? Please describe

I sometimes forget to change `nozzle_diameter` in klipper config after switching nozzle. Most of times it works, but when I switch to a large nozzle, sometimes I will get `move exceeds extrusion` error in the middle of the print and it was frustrating.

### Describe the solution you'd like

I hope fluidd can display the nozzle size in the main interface so that I get a reminder of this setting. 
Or even better, be able to configure it from the UI. 

### Describe alternatives you've considered

I think perhaps klipper could have do a dry run on the gcode file to raise these `move exceeds extrusion` error before the actual print. But I'd imagine that to be quite some work, and won't work for manually entered commands. Displaying the `nozzle_diameter` is probably cool and presumably easier in fluidd?

**Comment by pedrolamas** [comment]
Hi @thisiscam, thank you for your suggestion!

I have yet to properly look at how this would be implemented, but I think you can actually do something right now to mitigate your issue!

Assuming you are using some sort of `START_PRINT` macro in your slicer, you can add a parameter with the nozzle size to the macro, and then in the macro code compare that with what Klipper is currently set to, and if they differ, just do a `CANCEL_PRINT` to stop even before the print starts!

```
[gcode_macro START_PRINT]
gcode:
  {% set NOZZLE_DIAMETER = params.NOZZLE_DIAMETER | default(0) | float %}
  {% if NOZZLE_DIAMETER != printer.configfile.settings.extruder.nozzle_diameter | float %}
    M117 Klipper nozzle_diameter set to a different value than slicer!
    CANCEL_PRINT
  {% endif %}
  ....
```

**Comment by thisiscam** [comment]
Wow thanks! That solves it! Feel free to close the issue if you think implementing is just over-engineering.

**Comment by pedrolamas** [comment]
I think this is one of those that can be easily fixed with macro's, so let's take that approach!

One day we might have a fully featured Klipper config editor, but we are not there yet! 😉
