### ISSUE TITLE
Macros - default parameters are not populating when read from object i.e. printer['configfile']

### ISSUE THREAD

**Issue by camerony** [fluidd-core/fluidd#650]
### Browser

Chrome

### Device

Desktop PC

### Operating System

Windows

### What happened

The menu to populate the default parameter for a macro is not able to use values from objects.  It's showing the name of the object instead i.e. "printer.configfile.settings.printer.max_velocity"

### What did you expect to happen

The value should populate from the object i.e. printer.configfile.settings.printer.max_velocity should show the max velocity i.e. 300

### How to reproduce

```
[gcode_macro TEST_SPEEDABX]
gcode:
    {% set max_velocity = printer.configfile.settings.printer.max_velocity %}
    {% set speed = params.SPEED|default(max_velocity)|int %}
    M118 {speed}
```

<img width="218" alt="Screenshot 2022-04-29 090540" src="https://user-images.githubusercontent.com/1082654/165982062-5fcc1c41-e24e-4fd7-8b70-168e16697c53.png">

**Comment by pedrolamas** [comment]
That's just how Klipper macros work, as they are evaluated at runtime only!

You can however try something like this:

```
[gcode_macro TEST_SPEEDABX]
gcode:
    {% set max_velocity = printer.configfile.settings.printer.max_velocity %}
    {% set speed = params.SPEED %}
    {% set speed = speed|default(max_velocity)|int %}
    M118 {speed}
```

**Comment by camerony** [comment]
Unfortunately that doesn't work.  I could have sworn this used to work.

<img width="237" alt="image" src="https://user-images.githubusercontent.com/1082654/165996619-44171af2-d8bb-4361-b031-076c5b6aa799.png">

**Comment by pedrolamas** [comment]
That actually worked as I expected: what you show on the screenshot is the hint text, so the field is empty (just click on it)

**Comment by camerony** [comment]
hmm, interesting.  are you sure it never worked?  maybe klipper change the way it evaluated.  Andrew Ellis' macro uses this "https://github.com/AndrewEllis93/Print-Tuning-Guide/blob/main/macros/TEST_SPEED.cfg"

**Comment by pedrolamas** [comment]
Ah, I think I now see what you mean: we improved the defaults parsing a few versions ago, so now it can actually parse this default and show it, but as this is a variable and not a string, it's actually showing the wrong value!

The solution for now is using it like I showed above, at least until I have the chance to check the regular expressions on this!

**Comment by pedrolamas** [comment]
Issue caused by #566
