### ISSUE TITLE
Render MD files

### ISSUE THREAD

**Issue by digitalninja-ro** [fluidd-core/fluidd#656]
### Is your feature request related to a problem? Please describe

The Docs tab from Configuration shows only raw sources for .md files. It's nice to have all the documentation at a click distance but it's not so human readable.

### Describe the solution you'd like

Will be more handy to render the md files in fluidd in case I want a quick reference or don't have an internet connection to access the nice formatted documentation from klipper website or git repo.

**Comment by pedrolamas** [comment]
I've given a quick try on this and actually got it to render markdown, but this made me think that we probably should instead just link directly the open document file to the Klipper website instead... that way we ensure that users are looking at the latest documentation available!

**Comment by digitalninja-ro** [comment]
Thank you for your answer but I think the documentation is also updated and pushed with regular commits. If an user has an older version of klipper on pi  he also has the local documentation for his version of klipper.   It's not hard to have a tab open with klipper website or git but as long as we have the documentation on local machine how difficult is to make it more human readable?

**Comment by pedrolamas** [comment]
Well, it is possible... though at the moment, links don't work, images don't work...

![image](https://user-images.githubusercontent.com/85504/169153374-a8178b84-c589-448a-9475-5e5cbd898c56.png)

**Comment by thijstriemstra** [comment]
+1
