### ISSUE TITLE
Temperature limit wrong

### ISSUE THREAD

**Issue by gfarcas** [fluidd-core/fluidd#670]
### Browser

Chrome

### Device

Desktop PC

### Operating System

macOS

### What happened

Fluidd shows temperature limit active, but the system show's a different temp
<img width="1317" alt="Screenshot 2022-05-13 at 10 03 40" src="https://user-images.githubusercontent.com/8426011/168231777-9e14d70a-6044-47f7-b105-14c28169b924.png">

### What did you expect to happen

To show the system temp

### How to reproduce

I don't know

**Comment by matmen** [comment]
The notification shows the temperature the limit first triggered at, so this is intended behavior. I don't think it's worth refactoring the notification system just to show an up-to-date temperature (and you can already [show the current temperature in the temperature graph](https://www.klipper3d.org/Config_Reference.html#host-temperature-sensor), too). @pedrolamas Thoughts?

**Comment by gfarcas** [comment]
> The notification shows the temperature the limit first triggered at, so this is intended behavior. I don't think it's worth refactoring the notification system just to show an up-to-date temperature (and you can already [show the current temperature in the temperature graph](https://www.klipper3d.org/Config_Reference.html#host-temperature-sensor), too). @pedrolamas Thoughts?

I have checked the temp seconds after the notification, I don't think it dropped 10 degrees so fast

**Comment by matmen** [comment]
Your Pi must have reached 80°C for a short time (assuming you're running a RPi 4), the throttling warning only gets triggered >80C by the Pi directly (the status is retrieved via vcgencmd). It probably spiked at 81C and then went down again.

**Comment by matmen** [comment]
For reference: The throttle state is read by moonraker by running `vcgencmd get_throttled`, the core temperature is read from the `/sys/class/thermal/thermal_zone0/temp` file.

**Comment by matmen** [comment]
Is this still an ongoing issue or would you consider this solved?
