### ISSUE TITLE
Button and test color issues on the white theme

### ISSUE THREAD

**Issue by aka13-404** [fluidd-core/fluidd#673]
### Browser

Chrome

### Device

Desktop PC

### Operating System

Windows

### What happened

![image](https://user-images.githubusercontent.com/51682059/168441112-014f2606-8a60-4d80-a503-2569906fbfe6.png)
The print file button is dark, while it should be the accent color? Not sure. 

![image](https://user-images.githubusercontent.com/51682059/168441136-29f198a9-f8cc-4a28-8d6b-05ca73758a99.png)
The text in the notification boxes is white on white, so it is not readable. 

### What did you expect to happen

I would expect the text to be readable and the button a more fitting color :)

### How to reproduce

Switch to the light theme.

### Additional information

Appreciate your time and effort.

**Comment by matmen** [comment]
For tracking: looks like the same issue exists for the mobile file editor:
![image](https://user-images.githubusercontent.com/25269274/168441928-020ca8fe-d2fd-421a-8cee-a8ceae863f45.png)
