### ISSUE TITLE
Using two machines at the same time will report an error

### ISSUE THREAD

**Issue by Cloud2702** [fluidd-core/fluidd#675]
### Browser

Edge

### Device

Desktop PC

### Operating System

Windows

### What happened

![1](https://user-images.githubusercontent.com/85711992/168472113-f93b06ea-d890-4694-a7a6-6e910d42d43b.png)
![2](https://user-images.githubusercontent.com/85711992/168472114-01d2e0eb-14cd-4db2-a7ad-fa332a058ad3.png)

Two machines can not be used at the same time, such as A machine in use, and then switch another B machine has an error, even after restarting FIRMWARE A machine will report an error (Failed automated reset of MCU 'opi')

### What did you expect to happen

Hope to solve this problem of using multiple machines at the same time

### How to reproduce

No idea

### Additional information

fluiddv1.17.2
klipperv0.10.0-431

**Comment by matmen** [comment]
I don't think this is a fluidd bug - the warnings shown are just directly from Klipper. I assume you have misconfigured one of the printers (maybe you're using the same device ID for both printers? What's your `serial` value in the `[mcu]` block of both of your `printer.cfg` files?). You're probably better off [asking the Klipper community](https://www.klipper3d.org/Contact.html) for help.

**Comment by matmen** [comment]
Are you still facing this issue or were you able to solve it?

**Comment by Cloud2702** [comment]
Has been solved to find out the adxl345 accelerometer opi problem
