### ISSUE TITLE
Extended Gcode viewer auto-actions

### ISSUE THREAD

**Issue by matmen** [fluidd-core/fluidd#730]
### Is your feature request related to a problem? Please describe

For tracking: as requested in https://github.com/fluidd-core/fluidd/pull/696#issuecomment-1140531306

### Describe the solution you'd like

The following two settings in either the gcode viewer dropdown or fluidd's main settings:
* automatically load current file on print start
* automatically follow progress on file load

**Comment by pedrolamas** [comment]
Good one, and I can see this being quite useful for the "object cancellation" feature too!
