### ISSUE TITLE
Wrong documentation linked in the config editor

### ISSUE THREAD

**Issue by aka13-404** [fluidd-core/fluidd#741]
### Browser

Chrome

### Device

Desktop PC

### Operating System

Windows

### What happened

The config manager tries to link sections of the telegram.conf to the klipper documentation. 
![image](https://user-images.githubusercontent.com/51682059/177265967-fee37b17-3bb4-4e72-9243-8588bd0cfdcc.png)

### What did you expect to happen

I would expect it to not link anywhere.
Ideally I would like for fluidd to link to our official documentation, https://github.com/nlef/moonraker-telegram-bot/wiki/Sample-config#bot for example. 

### How to reproduce

Add a telegram.conf file with any section as on the screenshot.

**Comment by pedrolamas** [comment]
@nlef are we ok to link to `https://github.com/nlef/moonraker-telegram-bot/wiki/Sample-config#[section_name]` or should we just disable Codelens support for telegram.conf?

**Comment by nlef** [comment]
> @nlef are we ok to link to `https://github.com/nlef/moonraker-telegram-bot/wiki/Sample-config#[section_name]` or should we just disable Codelens support for telegram.conf?

This is a valid config url. Codelens will help users a lot, so it should not be disabled.
Thanks.

**Comment by aka13-404** [comment]
You are a magician Pedro, what would we do without you!
