### ISSUE TITLE
Подключение 2 принтеров к Raspberry pi

### ISSUE THREAD

**Issue by Fiilliin** [fluidd-core/fluidd#760]
### Is your feature request related to a problem? Please describe

С помощью KIAUH установил 2 комплекта клиппера, мунракера и флюида. 
![2022-07-12_10-11-12](https://user-images.githubusercontent.com/62616840/178457404-fc96937a-1dbf-4e6a-aa49-647bfa24882f.png)
При установке присвоил принтерам имена (anet и ebot). открываю браузер, ввожу 192.168.1.41/anet или 192.168.1.41/ebot - результат одниаков - я постоянно нахожусь на одном принтере, на второй он не переключается. Подскажите, что я делаю не правильно и как это починить?

### Describe the solution you'd like

Управление обоими принтерами из браузера

**Comment by matmen** [comment]
You can add another printer using the side menu, accessible via the 3 dots in the top right corner. There's a button to add another printer, as the URL you will need to set set `192.168.1.41:[port]`, replacing `[port]` with whatever port you set in your 2nd instances moonraker configuration.
Let me know if you need additional support 😉

**Comment by Fiilliin** [comment]
Есть ли возможность управлять одновременно двумя принтерами? т.е. открыть 2 вкладки браузера - на одной один принтер, на другой второй принтер.

**Comment by matmen** [comment]
It's not really supported as of now (reloading the 1st printers page would set it to use the 2nd printer), but it should still work if you open two tabs and switch to the other printer on the 2nd tab. Alternatively you can open an incognito browser window for the sessions to not collide.
Proper support for multi-printer management is already planned.
