### ISSUE TITLE
UI for manual bed levelling

### ISSUE THREAD

**Issue by rsheasby** [fluidd-core/fluidd#761]
### Is your feature request related to a problem? Please describe

I recently got an Ender 3 S1 Pro, and unfortunately got unlucky with a misbehaving CRTouch. Repeatability is fine, but there's probe location bias that I haven't been able to track down. No major problem though, as I can create a manual mesh that works pretty damn well. However, the lack of a UI wizard or utility makes this really annoying to deal with in fluidd. Manually typing in the TESTZ commands is painful and makes the whole process much slower.

### Describe the solution you'd like

A simple UI that provides easy and quick methods for starting a manual mesh level and issuing the testz commands to find the right height.

It doesn't need to be very complex, just a simple layout to start the process, then 6 buttons to move the head up and down by various amounts (1mm, 0.1mm, 0.01mm). I've found what works well for me is going down 1mm at a time until the nozzle touches the paper, then going up 0.1mm at a time until the paper moves freely, then going down 0.01mm until the paper touches again.

### Describe alternatives you've considered

Creating macros for issuing the correct commands does work, but the layout is cumbersome and makes it slower to work through a larger mesh. Ideally the UI would be as easy as possible to encourage people without ABL (or with broken ABL) to actually create and update a bed mesh instead of relying purely on corner levelling.

**Comment by pedrolamas** [comment]
Related to #782

**Comment by pedrolamas** [comment]
Adding a few options for layout here...

## Option 1

![image](https://user-images.githubusercontent.com/85504/180454145-0abb9331-d1e3-4b95-968c-1e1a40f365c6.png)

## Option 2

![image](https://user-images.githubusercontent.com/85504/180454280-e6eac4f0-43de-4a3c-9191-814ce62b934f.png)

@matmen @BastelKlug thoughts?

**Comment by BastelKlug** [comment]
I like the second option more. But shouldn't you replace the - and + icon with this:
![image](https://user-images.githubusercontent.com/44060099/180455521-5b374e65-2188-463c-b01d-b4a5c6fc986d.png)

**Comment by pedrolamas** [comment]
A good point... the only reason I went with `-` and `+` was to show exactly what it will send on `TESTZ Z=*`

**Comment by matmen** [comment]
I think option 3 looks the best, but maybe the buttons groups can line up? 
![image](https://user-images.githubusercontent.com/25269274/180491169-a3520024-47a3-4c18-adf6-bea6a211eaa6.png)
![image](https://user-images.githubusercontent.com/25269274/180491954-5ec519fa-8591-4c56-9ec5-de8129904752.png)

As for the icon, I think both +/- or the material design icons would work..
