### ISSUE TITLE
Add watermark to timelapse render

### ISSUE THREAD

**Issue by GTBannon** [fluidd-core/fluidd#767]
### Is your feature request related to a problem? Please describe

I currently export the timelapse into *video editor* and overlay a watermark on it. I then upload to social medias. I would like to be able to upload a photo of x * y pixels (opacity & logo location will be pre-determined based off the aspect ratio of my camera).

### Describe the solution you'd like

A front "layer" to the render process where a png or jpeg can be uploaded so that renders are pre-watermarked. Functionality to turn that layer on & off would also be nice.

### Describe alternatives you've considered

Export file to Camtasia, add file to layer 2 & extend for length of film. Export as MP4 to drive

### Additional information

Is there a different place this request should go? should that be something I should try to find a feature request on moonraker's timelapse github?

**Comment by pedrolamas** [comment]
Fluidd is just a web interface running on the web browser, so we don't have any control over such a feature.

My recommendation is that you open a Feature Request directly on the [moonraker-timelapse](https://github.com/mainsail-crew/moonraker-timelapse) repo.
