### ISSUE TITLE
hide backups in configuration tab

### ISSUE THREAD

**Issue by ReinBentdal** [fluidd-core/fluidd#768]
### Is your feature request related to a problem? Please describe

the configuration tab fast gets clogged with many backup files, as seen in the screenshot
<img width="724" alt="image" src="https://user-images.githubusercontent.com/21336626/179327887-61f0ef5b-8d48-43fa-beec-cc33f852bcd3.png">

### Describe the solution you'd like

having a simple option to hide backup files. Not sure how best to implement it. At least possible to identify the number format and in that way determine if its a backup or not

### Describe alternatives you've considered

Backup files could even be its own tab under "other files"
<img width="711" alt="image" src="https://user-images.githubusercontent.com/21336626/179328016-81dc935f-ec02-47dc-9505-2ae5b6a2fcb5.png">

**Comment by matmen** [comment]
There's a PR open for Klipper that allows backups to be moved to a different directory (https://github.com/Klipper3d/klipper/pull/5643). If it doesn't get merged I'm sure we can add a way to hide them :)
