### ISSUE TITLE
After recent update I get a save config and restart just from a print with no other config changes

### ISSUE THREAD

**Issue by sprior** [fluidd-core/fluidd#769]
### Fluidd Version

v1.19.0-6184c73

### Browser

Firefox

### Device

Desktop PC

### Operating System

Windows

### What happened

I like the recent changes to Fluidd, but now when I just turn the Voron on and run a print job a banner appears up top and then becomes enabled to save config and restart even when I have made no config changes, so I'm not sure what the difference would be.  As part of my print_start macro I do QGL, auto-z-calibration, and bed mesh (which gets cleared at the end of the print), so I don't know if one of those things is getting picked up as a config change to save, but I don't think it should be.

### What did you expect to happen

I don't think that just printing something should trigger an enabled save config and restart banner item.

### How to reproduce

I think I covered this in "What Happened"

**Comment by matmen** [comment]
I assume this would be because of bed mesh calibration, but I'm sure we can add an option to toggle the button off 😉

**Comment by pedrolamas** [comment]
@sprior out of curiosity here, but if you enable the "Review Pending Configuration Changes before Save and Restart" setting and then click on the "Save config and restart" button, what do you get there? Can you share a screenshot please?

**Comment by sprior** [comment]
@matmen @pedrolamas  I checked and it is bed mesh. 
![Screenshot 2022-07-16 210412](https://user-images.githubusercontent.com/3361800/179379784-5f1edf9a-241f-4b12-be87-a7cb7a8bf8d5.jpg)

**Comment by pedrolamas** [comment]
> I checked and it is bed mesh.

I guess a quick fix right now would probably be to add a `BED_MESH_CLEAR` to your "end print" macro!

**Comment by matmen** [comment]
That would still show the button during printing.. I'm fine with adding a toggle for the button here, though of course that wouldn't just hide the button completely instead of just for bed mesh changes..

**Comment by sprior** [comment]
@matmen I think I'd agree with a toggle to hide this button completely - for me when I'm actually making config changes that's something I'm doing very deliberately so I seek out the button to save those changes and when I'm not doing that I'd be super careful before saving config changes I didn't do very carefully.

**Comment by pedrolamas** [comment]
I see 3 ways of moving here:

- add toggle that would work as such:
  - never show **OR**
  - show when has changes
- add 3 state option (dropdown), with the following:
  - never show **OR**
  - show when has changes, but not during busy/printing **OR**
  - show when has changes
- do nothing and assume current behavior as expected

I think the toggle would work best (I see no need to hide during print, disabling is good enough!)

**Comment by sprior** [comment]
I'll use the vote I don't have to pick the first option.
