### ISSUE TITLE
`width` attribute for the `<iframe>` (Cameras/Stream Type/HTTP page)

### ISSUE THREAD

**Issue by balthisar** [fluidd-core/fluidd#778]
### Is your feature request related to a problem? Please describe

When adding cameras via the Fluidd UI, we have the option to specify a stream type with the value HTTP page, which will load a website via an `iframe` instead of a direct camera feed. The requirement to specify the height of the `iframe` functions, but because no width is specified in the rendered `iframe`, the iframe is defaulted to 300px, which presents a poor aspect ratio. For example:

```
<iframe data-v-3b58d080="" src="https://prettygcode.local/" height="480" frameborder="0" class="camera-image"></iframe>
```

Please see screencap "Additional information" field, below.

### Describe the solution you'd like

Either:

* Apply a fixed, `width="100%"` to the `iframe`, e.g.,

    `<iframe data-v-3b58d080="" src="https://prettygcode.local/" height="480" width="100%" frameborder="0" class="camera-image"></iframe>`

* Or add the ability to provide a user-specified width to the Add Camera UI.

### Describe alternatives you've considered

None.

### Additional information

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/3053246/179870385-861f609d-0c75-476f-a4e6-74dd3bd0eb04.png">

**Comment by ayufan** [comment]
@balthisar Thanks for this issue.

I'm facing the same problem that I noticed while working on `WebRTC` feed to https://github.com/ayufan-research/camera-streamer/tree/webrtc#webrtc-support. The `width: 100%` seems to do the trick.

![image](https://user-images.githubusercontent.com/2419009/187775616-4475f54d-f39d-4f3f-8c81-f5ecfdbce241.png)

**Comment by ayufan** [comment]
Also to add to this: `<iframe` should be run in a sandbox mode to avoid passing relevant data from the current browser session.

**Comment by ayufan** [comment]
However, this might not be good way. Whether we need width or heigh does depend on screensize. This is how it looks on iOS.

![IMG_68D8AB05CC8C-1](https://user-images.githubusercontent.com/2419009/187781599-36f08088-336e-4d65-934e-9850661f7862.jpeg)

**Comment by Noguai** [comment]
I'm also using the iframe camera type to embed a WebRTC stream and have pretty much the same issue. 

Though I think for the purpose of embedding camera streams, setting a specified aspect ratio would be much more useful than a specific width/height as it is now. That way the card containing the stream would be properly displayed regardless of screen size or desktop or mobile use.

My current workaround for this is to set the iframe height in the camera settings to `-1` and manually change the style sheet for the iframe (by editing the respective css file on the raspberry) as seen in the screen shot below:

![image](https://user-images.githubusercontent.com/10562439/189480798-c335ed07-5d1e-418d-bf92-62b7184178c9.png)

**Comment by matmen** [comment]
The iframes now fill the elements width in the newest release.
In the next release we're going to implement aspect-ratio based sizing (still filling the available width (because it's the static component here), but with a height derived from that width; it hasn't landed in this release yet because it's a breaking change, see #867).

**Comment by ayufan** [comment]
Wow. Thank you @matmen!

**Comment by ayufan** [comment]
This works great now.
