### ISSUE TITLE
migrate to vite

### ISSUE THREAD

**Issue by BastelKlug** [fluidd-core/fluidd#796]
### Is your feature request related to a problem? Please describe

vue-cli is really slow while developing and many packages have been discontinued.

### Describe the solution you'd like

switch from vue-cli to vite.

**Comment by pedrolamas** [comment]
I like this idea, but I have to say I've taken a look into this a while back, however I stopped when I noticed that the Monaco editor wasn't working (granted, I didn't put much effort into investigating why it wasn't working!)

Having said that, we might also want to consider upgrading to Vue3 when Vuetify supports it (currently only Vue 2 is supported and the recommendation it to wait for proper Vue 3 support)
