### ISSUE TITLE
Upload & Start button

### ISSUE THREAD

**Issue by BastelKlug** [fluidd-core/fluidd#804]
### Is your feature request related to a problem? Please describe

Uploading and printing .gcode files takes too long.

### Describe the solution you'd like

Add a button like on Duet Web Control to start prints faster.
I think it will the best in a similar style to the notification bell

Like this: (A)

<img width="298" alt="Bildschirmfoto 2022-07-30 um 00 51 02" src="https://user-images.githubusercontent.com/44060099/181855240-54622aff-eb68-4d45-990a-a01829189544.png">

or: (B)

<img width="298" alt="Bildschirmfoto 2022-07-30 um 00 47 51" src="https://user-images.githubusercontent.com/44060099/181855008-cedce2f7-72cd-4afb-ab72-a689b8f31c1b.png">

### Additional information

<img width="580" alt="Bildschirmfoto 2022-07-30 um 00 33 36" src="https://user-images.githubusercontent.com/44060099/181853924-7ece80f7-35a2-438f-b28a-81e9beff7f68.png">

**Comment by BastelKlug** [comment]
I personally like figure A more, but it looks strange with the save & restart button.

In the worst case it looks like this:
<img width="549" alt="Bildschirmfoto 2022-07-30 um 19 54 23" src="https://user-images.githubusercontent.com/44060099/181935701-05fa5565-a632-4ed5-8ffc-5aebdc3b4f6e.png">

Any suggestions? @matmen @pedrolamas

**Comment by pedrolamas** [comment]
Not fond of having it in blue, that's my main take!

Having said that, I think that that area is starting to get a bit overcrowded, so we need to start considering that too.
