### ISSUE TITLE
Fluidd not always updating information with new print

### ISSUE THREAD

**Issue by fredconex** [fluidd-core/fluidd#805]
### Fluidd Version

v1.19.0

### Browser

Chrome

### Device

Desktop PC

### Operating System

Windows

### What happened

When using SuperSlicer to send a new file to print (not tested with other slicers) it does send the new file but some info on fluidd does not update with new file/print.

### What did you expect to happen

Loading a new print should update info, times and thubnail.

### How to reproduce

Can't say for sure, but I got it happening randomly when just changing objects on the plate and sending to print, filename remain the same and just objects/gcode change, maybe as filename is same its not understanding that it's a new print?

The print is under progress, fluidd didn't display correct information
![image](https://user-images.githubusercontent.com/109859677/181859422-b1b1b691-a0d7-42e2-a245-240e4d5032c3.png)

So I've pressed refresh button on browser, then it updated the information
![image](https://user-images.githubusercontent.com/109859677/181859409-fdb57327-59d1-4f64-b5ad-8fad7d6a9c17.png)

**Comment by sarthurdev** [comment]
Noticed the same issue when using gcode preview. If restarting a print with the same filename but having changed settings in slicer, the gcode viewer won't reload and load button remains disabled.

**Comment by pedrolamas** [comment]
I've found and fixed the issue reported by @fredconex (there's now a PR going under review with the fix).
