### ISSUE TITLE
FORCE_MOVE moves the printer without acceleration!

### ISSUE THREAD

**Issue by marcocipriani01** [fluidd-core/fluidd#814]
### Fluidd Version

1.19.1

### Browser

Chrome

### Device

Desktop PC

### Operating System

Windows

### What happened

Using the new `FORCE_MOVE` Fluidd feature, the toolhead moves without accelerating because the optional `ACCEL` parameter is never used:

![image](https://user-images.githubusercontent.com/20319029/183244153-d00d9c72-a405-45de-b352-6d1f619b2c5a.png)

According to the Klipper docs, the full syntax for the `FORCE_MOVE` command is:

`FORCE_MOVE STEPPER=<config_name> DISTANCE=<value> VELOCITY=<value> ACCEL=<value>`

This causes the toolhead to go at full speed immediately. My poor Anycubic i3 Mega didn't like it and only made noise instead of moving. Please retrieve the correct acceleration value from the printer limits and set it in the `FORCE_MOVE` commands.

Thanks!

### What did you expect to happen

Printhead accelerating.

### How to reproduce

Press on `FORCE_MOVE` and move the printer with the controls below.

**Comment by pedrolamas** [comment]
Very good point, we will add this for next version.
