### ISSUE TITLE
Internal file editor fails to load on MS Edge browser

### ISSUE THREAD

**Issue by cobyn** [fluidd-core/fluidd#821]
### Fluidd Version

1.19.1

### Browser

Edge

### Device

Desktop PC

### Operating System

Windows

### What happened

Openeding a file in configuration shows a blank screen, looking at console log i see this error every time i open a file.
![image](https://user-images.githubusercontent.com/2914460/183764739-cdf2c3a8-1169-45b9-bcb9-cb2a0e489ab7.png)
 
This only is happening on my windows 11 machine running Chromium Edge seem to work fine on android chrome and windows 10 edge. 

### What did you expect to happen

file editor opens with the content of the file

### How to reproduce

try opening a file in configuration manager while on edge on windows 11

**Comment by pedrolamas** [comment]
Thank you for reporting this, I have an idea of what this might be!

Please check the following:

- In the address bar, click the small icon that appears just left of the address
- On the popup, click the "Enhance security for this site"
- Disable the "Use enhanced security for this site"
- Refresh the page and try again.

Can you follow these steps and report back if that fixed the issue please?

**Comment by cobyn** [comment]
Nice that fixed it!

**Comment by pedrolamas** [comment]
Thanks for confirming it, I had suspected this was the case as Microsoft seems to have changed what non-HTTPS sites can do (and in this case, block them from running Web Assembly bits)

Guess we need to add some new instructions for Edge browser...
