### ISSUE TITLE
Export & Import Fluidd "Settings" page

### ISSUE THREAD

**Issue by jhlchu** [fluidd-core/fluidd#826]
### Is your feature request related to a problem? Please describe

Recently had to re-install klipper and fluidd from because of a bad update. I have many macros and organized them into categories in the "Settings" (http://fluiddpi.local/#/settings) page, now it's all gone. This includes re-assigning Alias, Category, Color, Disable while Printing, and Visibility.

### Describe the solution you'd like

Simple export and import button. Or at the very least have settings config written to file in ~/ so it's easy to copy and paste.

### Describe alternatives you've considered

Possible to backup with KIAUH but it would have also backed up the corrupted fluidd config not just the settings.

**Comment by pedrolamas** [comment]
Hi @jnimety, Fluidd settings are stored on Moonraker database, and you can actually make a full backup of it just by copying the hidden "~\.moonraker_database" folder.

Given the above procedure, at this stage I don't think there is the need for an export & import Fluidd settings feature, so will close this ticket.
