### ISSUE TITLE
Option to hide '.gcode' and '_' from file names in Jobs Menu

### ISSUE THREAD

**Issue by ChaosBlades** [fluidd-core/fluidd#886]
### Is your feature request related to a problem? Please describe

A super duper important feature request.

### Describe the solution you'd like

Settings > General
Add option to 'Hide extensions and underscores from Jobs Menu.

Removes `.gcode` from end of file name and replaces `_` with ` `.

### Describe alternatives you've considered

Just remove them by default. I see no reason they should exist other than it requires effort to code them out.

### Additional information

Can you tell I'm OCD?
It just makes the best looking printer WebUI look just a little bit cleaner.

**Comment by matmen** [comment]
I'm going to close this for now, the side effects are outweighing the benefits here as of now (see https://github.com/fluidd-core/fluidd/pull/893#issuecomment-1271628228).
