### ISSUE TITLE
Unknown command:"Z_OFFSET_APPLY_ENDSTOP"

### ISSUE THREAD

**Issue by ksdfpr** [fluidd-core/fluidd#889]
### Fluidd Version

1.20.1

### Browser

Firefox, Safari, Edge

### Device

Desktop PC, Mobile device (Phone, Tablet or similar)

### Operating System

Windows, macOS, iOS

### What happened

I get the following error [Unknown command:“Z_OFFSET_APPLY_ENDSTOP” ] when Im trying to update z offset from fluidd interface save button.
I have a delta kossel printer with manual probe system (microswitch), delta printers don’t have a z endstop

### What did you expect to happen

To update z_offset permanently after SAVE_CONFIG

### How to reproduce

Changing values via buttons 
Press save button

![εικόνα](https://user-images.githubusercontent.com/59396230/193652306-e7805dff-a0da-4655-ba7f-36093c2d2c09.png)

![εικόνα](https://user-images.githubusercontent.com/59396230/193652157-c992f9de-ba6b-4271-a7c7-c18615172173.png)

### Additional information

Maybe for delta printers  the command  Z_OFFSET_APPLY_PROBE works?...

**Comment by pedrolamas** [comment]
Thank you for your report @ksdfpr, can I ask that you upload your printer.cfg file please?

**Comment by ksdfpr** [comment]
Yes, sure. Please rename .txt to .cfg
[printer.txt](https://github.com/fluidd-core/fluidd/files/9700258/printer.txt)
