### ISSUE TITLE
Auto-scrolling to bottom of console breaks with multiple M118.

### ISSUE THREAD

**Issue by gauravmm** [fluidd-core/fluidd#904]
### Fluidd Version

1.7.0-f1b32a9

### Browser

Chrome, Firefox

### Device

Laptop, Mobile device (Phone, Tablet or similar)

### Operating System

Windows, Linux

### What happened

When a macro emits multiple M118 commands in rapid succession (or a plugin prints data with multiple lines) the console scroll no longer sticks to the bottom and no longer follows output.

### What did you expect to happen

I expect the console to continue remaining "stuck" to the newest output.

### How to reproduce

Define the macro:
```
[gcode_macro TEST_MULTILINE_M118]
gcode:
    M118 LINE 1
    M118 LINE 2
    INVALID_COMMAND
    M118 LINE 3
    M118 LINE 4
```

Run the command `TEST_MULTILINE_M118` repeatedly in the console until it fills the console view. The next invocation of `TEST_MULTILINE_M118` will stop scrolling partway through the output.

(This was first observed with the automatic z-calibration Klipper plugin, and can be seen there.)

### Additional information

Looking into `src/components/widgets/console/Console.vue`, the issue seems to be the `      this.updateScrollingPaused()` at the end of `scrollToLatest`.

Control flow only reaches that call if scrolling is not already paused, so there is no need to call `this.updateScrollingPaused()` to check if scrolling should be paused or unpaused after scrolling to the bottom. Commenting this one line out fixes the issue and does not appear to cause any problems.

Let me know if you'd like me to submit a pull request for this one-liner.

**Comment by matmen** [comment]
This doesn't seem to happen with the flipped console layout turned on, hence why I couldn't reproduce #877.
Thanks for the report and repro.
