### ISSUE TITLE
Add 1 more decimal place to Temperature Rate of Change

### ISSUE THREAD

**Issue by ChaosBlades** [fluidd-core/fluidd#907]
### Is your feature request related to a problem? Please describe

Noticing that a lot of times especially when cooling off the temperature rate of change is 0.0 c/s or rarely 0.1 c/s. Would be helpful if this if this was increased by 1 more decimal place, so 0.08 c/s instead of 0.0 c/s.

I am just trying to figure out if turning my circulation fans on when the print bed is cooling is helping or not and by how much but I am not getting enough data to tell for sure. It looks like it does by watching the bed temp but my rate of change is just slightly below 0.0 c/s, which isn't useful.

Not just when cooling. The default setting for bed power on a v2.4 voron is 0.6. After caculating the exact value based on "Rule of thumb is 0.4 watts / cm^2" I set my max power to 0.67. How much did this improve things? No idea both of then just list the rate of change as +0.1 c/s
![Screenshot from 2022-10-11 23-50-02](https://user-images.githubusercontent.com/7530545/195246027-0e1c2801-4ad3-475a-98e1-79ba599bc84e.png)

### Describe the solution you'd like

Just increase the decimal place by 1. So 0.00 instead of 0.0. Looks like there is more than enough space for this.

### Additional information

I think some more complex math would be needed to calculate this since it looks like klipper only reports temp to the tenth of a degree instead of hundredth?

Edit: The tooltip for the graph actually shows to the hundredth instead of tenth of a degree C. So this shouldn't be hard to implement. The data is already there.
![Screenshot from 2022-10-12 00-22-15](https://user-images.githubusercontent.com/7530545/195249594-c4f0b354-4ad1-4f42-a5cf-c8a3e291f42f.png)

**Comment by matmen** [comment]
Thanks for your request and sorry for the late response.
I'm not sure the added decimal place would really help here, as it wouldn't deliver reliable data and provide a false sense of accuracy.
For example, my mainboard has a 12 bit ADC, my thermistor a range of `-50°C` to `285°C` (`335°C` total range). In a perfect world, this would deliver an accuracy of `± (335°C / 2^12) ≈ 0.08°C`. Factoring in noise (induced noise into unshielded sensor wires, ADC noise, sensor drift, ...), this accuracy can never realistically be achieved.
Taking an average of a large(r) dataset (either a long period of time or a high update rate) would reduce the noise level impact, but fluidd currently only gets one data point per second.
I'll go ahead and close this request for now as this is not something we can currently do.
