### ISSUE TITLE
follow progress on gcode preview be displayed on header bar

### ISSUE THREAD

**Issue by dez1729** [fluidd-core/fluidd#926]
### Is your feature request related to a problem? Please describe

When selecting a layer or progress, it cancels the "follow progress", but in order to resume you have to click through to the gears icon menu in order to select it. This should be something that can be selectable on the header bar without going for the extra click.

### Describe the solution you'd like

The "follow progress" should be selectable on the gcode preview header bar.

**Comment by pedrolamas** [comment]
Thank you for your FR @dez1729, I agree and quite honestly, I think that whole panel needs an upgrade!

We will look into this the first opportunity we get!

**Comment by pedrolamas** [comment]
I've now started some work on this, here are two options I am currently experimenting with:

## Option 1

![image](https://user-images.githubusercontent.com/85504/204535448-0ee3cd54-2793-4bfc-b767-ef8e53286323.png)

## Option 2

![image](https://user-images.githubusercontent.com/85504/204535495-cf6be785-0f06-4a38-8ef4-fc194e171e06.png)

---

Both options will show tooltips on mouse hover, the 1st option seems to be cleaner but the 2nd option is a bit more accessible on the phone (as the buttons are kept closer)

**Comment by pedrolamas** [comment]
@matmen @BastelKlug any comments on the above? 🙂
