### ISSUE TITLE
Allow disabling of links to configuration documentation in the editor

### ISSUE THREAD

**Issue by balthisar** [fluidd-core/fluidd#938]
### Is your feature request related to a problem? Please describe

Recently the built-in file editor has started inserting blue “View 'xxx' documentation links”, which cannot be turned off (or at least, the new configuration setting controlling this is not present in the documentation). While it's valuable for some users, for others, they're redundant, visually disturbing, and seriously break up the flow and formatting of text documents.

For example:

<img width="892" alt="image" src="https://user-images.githubusercontent.com/3053246/199826545-bb3f739d-6d52-44a7-a3b1-7dee7d824832.png">

### Describe the solution you'd like

I would like a configuration option — either in one of the config files or in the browser — to turn off this new feature.

### Describe alternatives you've considered

I've considering ssh'ing and using vi for quick and dirty changes, or using BBedit (or another ssh-capable text editor) for file editing, but it's quite convenient to use the built-in editor from time to time.

**Comment by balthisar** [comment]
Never mind; apparently this is what "CodeLens" is in the options. At least this closed issue might help others when they search. And I'm an idiot; I simply didn't check before opening this.

**Comment by pedrolamas** [comment]
Glad you found the setting @balthisar, seems we need to improve documentation around this, so there is still a lot of value in this report! 🙂
