### ISSUE TITLE
after updating for v1.20.1 fluidd stopped responding, getting toast error: 'Directory does not exist (/home/pi/printer_data/gcodes)'

### ISSUE THREAD

**Issue by harellevy** [fluidd-core/fluidd#949]
### Fluidd Version

v1.20.1

### Browser

Chrome

### Device

Laptop

### Operating System

macOS

### What happened

after updating last time klipper to 1.20.1 (all shows as up to date),
Just connected today and got a toast error: 'Directory does not exist (/home/pi/printer_data/gcodes)'
and in the HOME i get this warnings:
Moonraker warnings found.
[server]: Option 'enable_debug_logging' is deprecated, see the configuration documention at https://moonraker.readthedocs.io/en/latest/configuration/
Unable to create data path folder at /home/pi/printer_data
[database]: Option 'database_path' is deprecated, see the configuration documention at https://moonraker.readthedocs.io/en/latest/configuration/
Reverting to legacy database path: /home/pi/printer_data/database
[file_manager]: Option 'config_path' is deprecated, see the configuration documention at https://moonraker.readthedocs.io/en/latest/configuration/
[file_manager]: Option 'log_path' is deprecated, see the configuration documention at https://moonraker.readthedocs.io/en/latest/configuration/
Failed to validate service: [Errno 2] No such file or directory: '/home/pi/printer_data'

nothing like uploading files, printing, changing configuration files doesn't work, restart firmware wasn't helping.

### What did you expect to happen

app initial or at least will let me to force version again (reinstall same version) or show new versions to download with fix.

### How to reproduce

install fluid 1.20.1, not in the right order might be the issue, we have too many update buttons, it's better the app will handle all the installation flow, and I would only select what to install.

### Additional information

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/2623446/201536916-8d2ab644-4191-4dcb-ba8a-c859a5978a16.png">

**Comment by harellevy** [comment]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/2623446/201536934-1baf4ba3-7a2b-44e0-8296-6d6a55b1502a.png">

**Comment by pedrolamas** [comment]
This is not a Fluidd bug, it is actually a know extra step when upgrading to the latest Moonraker.

You will need to follow the instructions shown in the warnings to get your printer back into working condition.
