### ISSUE TITLE
 Wrong HOST temp

### ISSUE THREAD

**Issue by kobzzon** [fluidd-core/fluidd#960]
### Fluidd Version

v1.21.1

### Browser

Chrome

### Device

Desktop PC

### Operating System

Windows

### What happened

Temp host in Fluidd displaying wrong

### What did you expect to happen

in ssh session host temp is Ok

### How to reproduce

![image](https://user-images.githubusercontent.com/95584234/203306543-0c003439-d66a-4528-96b2-5fc5d0c840d5.png)
![203297326-a036b8a1-a1b1-4a74-8ffd-5c667cb20393](https://user-images.githubusercontent.com/95584234/203306579-312b14af-452d-45b9-8b36-f0f24b61353e.jpg)

**Comment by pedrolamas** [comment]
What configuration section are you using to retrieve the host temperature?

Fluidd is just a web-interface and shows whatever Klipper provides (via Moonraker), so this in the end will be a Klipper issue, so not something we can fix here.

**Comment by pedrolamas** [comment]
Assuming you are using a `sensor_type: temperature_host` in your Klipper printer.cfg, you will most likely have to override the `sensor_path` as Klipper by default will use `/sys/class/thermal/thermal_zone0/temp` but that doesn't seem to be available in your system.

You can confirm by SSH'ing and then `cat /sys/class/thermal/thermal_zone0/temp` and checking the result

**Comment by kobzzon** [comment]
> cat /sys/class/thermal/thermal_zone0/temp

![Без имени](https://user-images.githubusercontent.com/95584234/203486034-5726c635-5f8e-46f3-971b-ec917cbf9579.jpg)

**Comment by pedrolamas** [comment]
I guess that confirms how the -1 appeared!

You will need to find out that the correct path is for your system and set that following the instructions on my post above.

**Comment by pedrolamas** [comment]
I am closing this now as I assume you've followed the required steps.

If you are still having trouble with this, I suggest jumping on [Klipper Discord](https://discord.klipper3d.org/) `#configuration` channel and following up on the matter there.
