### ISSUE TITLE
Settings to change Jobs sorting order

### ISSUE THREAD

**Issue by JacopoBassan** [fluidd-core/fluidd#966]
### Is your feature request related to a problem? Please describe

The Jobs panel orders files and folders by default by Modified date, and if we sort by name we get the same order as the **ls** command, in my use case (and I think most cases) it's very disorienting, for example I have:
```
~/gcode_files $ ls
10-Calibration  11-Upgrades  1-Cosplay  3-Models  4-Toys  5-Keychains  6-Home  7-Rings  8-Vases  9-Fusion360  Ender3
```

### Describe the solution you'd like

I think we should use the **-v** flag
```
~/gcode_files $ ls -v
1-Cosplay  3-Models  4-Toys  5-Keychains  6-Home  7-Rings  8-Vases  9-Fusion360  10-Calibration  11-Upgrades  Ender3
pi@chonkyraspy:~/gcode_files $ 
```

### Additional information

I prints lots of files that have multiple parts and keep my folders organised and synced so an option to change the sort behaviour would be great, I would definitely use name with the **ls -v** order. Thanks!

**Comment by pedrolamas** [comment]
HI @JacopoBassan , thank you for taking the time to submit this Feature Request.

Can I ask why don't you use 2 or even 3 digits (so instead of having "1, 2, 3..." you would have "001, 002, 003...")? That would surely maintain order as you require here!

**Comment by JacopoBassan** [comment]
Hi @pedrolamas, while I do get that I could do that, I'd have to rename more than just a couple of files and folders, I have a lot of files like part1, part2… part10 and I really don't see any use of an ordering that doesn't follow natural language ordering. Plus what's still missing is that at every refresh the UI uses the Modified date for default ordering :)

**Comment by pedrolamas** [comment]
Sorting just by numerical prefix is doable, and we are now working on a solution for that, but reproducing the full sort order used in `ls -v` is quite tricky...

To be honest, I haven't been able to find any specifics on the algorithm used!

**Comment by pedrolamas** [comment]
Spoke too soon: I found the rules for `ls -v` (and `sort -V`) https://github.com/coreutils/gnulib/blob/master/lib/filevercmp.h

Will now try to implement this...
