### ISSUE TITLE
Labels show translation ID's instead of the translated text

### ISSUE THREAD

**Issue by GP3DS** [fluidd-core/fluidd#971]
### Fluidd Version

1.22.0

### Browser

Safari, Other (Please tell us below)

### Device

Desktop PC, Laptop

### Operating System

macOS

### What happened

After updating from 1.21.1 to 1.22.0, the menu icons are no longer visible. The name code of the icons is replaced.

### What did you expect to happen

How to fix this bug?

Is it possible to explain to me how to fix this?

Thank you for your help

### How to reproduce

Just update from 1.21.1 to 1.22.0 (with the update of the operating system packages)

### Additional information

![Capture d’écran 2022-12-07 à 21 29 49](https://user-images.githubusercontent.com/100126805/206402071-fa804614-2e7a-4b1f-8e7d-379850dc3a99.png)
![Capture d’écran 2022-12-08 à 09 54 06](https://user-images.githubusercontent.com/100126805/206402397-4a0da6e8-a2d1-45d5-96bb-bfab44adf11e.png)
![Capture d’écran 2022-12-08 à 09 55 24](https://user-images.githubusercontent.com/100126805/206402587-6d5d7b21-a592-4ec2-993a-0e3076cb620b.png)
![Capture d’écran 2022-12-08 à 09 54 48
![Capture d’écran 2022-12-08 à 09 58 00](https://user-images.githubusercontent.com/100126805/206403115-730914a8-e5c4-4cf3-9cce-e825fd449b68.png)
![Capture d’écran 2022-12-08 à 09 58 49](https://user-images.githubusercontent.com/100126805/206403288-99ded6de-0427-486f-be25-9d2748b287e5.png)

](https://user-images.githubusercontent.com/10012680
![Capture d’écran 2022-12-08 à 09 57 16](https://user-images.githubusercontent.com/100126805/206402988-9eb2ecad-4b17-426d-9e37-38e6873bb0a6.png)
5/206402589-73613f17-5dd0-4446-bd7e-8ff535358e2a.png)
![Capture d’écran 2022-12-08 à 09 55 24](https://user-images.githubusercontent.com/1001
![Capture d’écran 2022-12-08 à 09 56 47](https://user-images.githubusercontent.com/100126805/206402894-a18c8aaf-b0dc-4d84-99dc-213c6fbfb969.png)
26805/206402629-f76f65e4-246e-4f61-8d9d-e12a68df97d2.png)

**Comment by pedrolamas** [comment]
Hi @GP3DS thank you for reporting this.

We've seen other users having the same issue but have yet to determine what is causing this behavior.

Having said that, some users found that they could mitigate this problem by doing a full browser refresh of Fluidd (with <kbd>Ctrl</kbd>+<kbd>F5</kbd>), then going on Fluidd Settings, changing the language to English, and then back to their chosen language and it would then work!

Can you please check if these steps also fixes the problem for you?

**Comment by GP3DS** [comment]
Thank you for your quick response.

I've been looking for a solution since yesterday morning... and you solved the problem in 5 minutes ;-)

The fact of moving from French to English and again from English to French solved the problem on my two machines!

Thank you very much for your help!!!

**Comment by pedrolamas** [comment]
I believe I found what caused this issue and have just pushed a fix for it in v1.22.1!
