### ISSUE TITLE
Ability to have gcode search perform in sub directories 

### ISSUE THREAD

**Issue by DKS-18** [fluidd-core/fluidd#976]
### Is your feature request related to a problem? Please describe

currently, search is only performed in the open folder of your code. If the desired file happens to be in a sub folder then it is ignored int the search results

### Describe the solution you'd like

the ability to have search also performed in sub-folders

**Comment by pedrolamas** [comment]
Hi @DKS-18, thank you for your Feature Request.

Fluidd is just a web interface, we use Moonraker as the server-side API provider and at the moment there isn't an endpoint that would provide such a behavior.

We could try and recursively issue a search on the server, but that is not a good approach to this problem, so we will need for Moonraker first to provide this functionality so we can integrate with it.
