### ISSUE TITLE
Moonraker requests are incorrectly served by the service worker cache

### ISSUE THREAD

**Issue by Desuuuu** [fluidd-core/fluidd#983]
### Fluidd Version

v1.22.1

### Browser

Firefox

### Device

Desktop PC

### Operating System

Windows

### What happened

I have Fluidd and Moonraker setup behind nginx on the same domain with the following configuration (fairly standard):

```
    root /home/printer/fluidd;

    index index.html;

    client_max_body_size 0;
    proxy_request_buffering off;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    location /websocket {
        proxy_pass http://127.0.0.1:7125/websocket;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 86400;
    }

    location ~ ^/(printer|api|access|machine|server)/ {
        proxy_pass http://127.0.0.1:7125$request_uri;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Scheme $scheme;
    }
```

The service worker registered by `vite-pwa` currently falls back to `index.html`, which causes direct requests to Moonraker to be incorrectly directed to Fluidd.

For example, opening `http://printer.local/server/info` (after the service worker has been registered) serves Fluidd instead of Moonraker.

### What did you expect to happen

The service worker should not handle requests that are not directed to Fluidd.

### How to reproduce

* Install Moonraker/Fluidd through Kiauh
* Open Moonraker (it should work at this point) `http://printer.local/server/info`
* Open Fluidd so the service worker gets registered `http://printer.local`
* Open Moonraker again `http://printer.local/server/info`
* The request is served by Fluidd

### Additional information

The `vite-pwa` fallback behaviour can be disabled by setting the `workbox.navigateFallback` option to `undefined`.

```diff
index 0549448..f411c2c 100644
--- a/vite.config.ts
+++ b/vite.config.ts
@@ -15,6 +15,9 @@ export default defineConfig({
   plugins: [
     VitePWA({
       registerType: 'autoUpdate',
+      workbox: {
+        navigateFallback: undefined
+      },
       includeAssets: ['img/**/*.svg', 'img/**/*.png'],
       manifest: {
         name: 'fluidd',
```

The fallback behaviour at the service worker level doesn't seem to be used in most (any?) cases, since nginx is used to do the same thing.

EDIT: I think the problem might only be occurring when using HTTPS due to browser security policies.

Setting the `unsafely-treat-insecure-origin-as-secure` flag on Chrome/Edge or `devtools.serviceWorkers.testing.enabled` on Firefox should help reproduce this without using HTTPS.

**Comment by pedrolamas** [comment]
Thank you for reporting this, @Desuuuu.

Though I have a similar setup, I haven't noticed this issue yet but will recheck on it now.

**Comment by pedrolamas** [comment]
> I think the problem might only be occurring when using HTTPS due to browser security policies.

That makes sense, as I believe HTTPS is a requirement for service workers (at least Vite PWA does mention it)

Settings `navigateFallback: undefined` makes sense and I can see the impact directly on the generated files, however I am trying to also understand the impact in terms of the Vue Router... normally one would have to ensure all routes are correctly served via index.html file, so I'd expect such change to impact at least on the offline more.

I've made a draft PR with your proposed change and will be performing more tested before merging this down, but we might need to use a different approach and instead either set an "allow list" with all of the Fluidd routes, or a "deny list" with all the others.

**Comment by pedrolamas** [comment]
That is a very good point: at the moment there is nothing that will work without a Moonraker connection, although I considered the offline feature as being able to run with just Fluidd offline.

At the moment, I personally think of Fluidd PWA functionally as a way to install as a native app, the rest of the PWA functionalities are not in actual use.

**Comment by pedrolamas** [comment]
@Desuuuu I've updated the PR to just use `workbox.navigateFallbackDenylist` and added all the Moonraker routes (matching the same ones you have on your nginx.conf shown here) to it.
