### ISSUE TITLE
Search does not show any results on Job list

### ISSUE THREAD

**Issue by idzuwan** [fluidd-core/fluidd#989]
### Fluidd Version

v1.22.2

### Browser

Firefox

### Device

Desktop PC

### Operating System

Windows

### What happened

When try to search Job/Uploaded Gcode it will not show any result
![search0](https://user-images.githubusercontent.com/7881146/208590759-9197c210-c2ee-4a96-98ef-5c3f7c9b3551.JPG)
![search1](https://user-images.githubusercontent.com/7881146/208590768-9a126c05-0125-437b-b44c-6e939f8c2da9.JPG)

same result on chrome or mobile

### What did you expect to happen

able to search uploaded gcode

### How to reproduce

using search function on the job list

### Additional information

I noticed it only started to happen but didnt remember exact day when

**Comment by pedrolamas** [comment]
Thank you for the report @idzuwan.

For the record, we've been aware of this issue for a while now, it is a [bug in Vuetify library](https://github.com/vuetifyjs/vuetify/issues/11600) we use and only became a problem for us with the changes from #812.

**Comment by idzuwan** [comment]
Hi @pedrolamas 

Thank you, it good to know that it is been work on at the moment

Rgds
Idzuwan
